konveyor/move2kube

Makefile
scripts/licensecheck.sh

increase lint timeout

---

internal/common/tar_test.go
internal/common/utils.go

Changed tests for TarAsString to be more robust against changes in file permissions

---

USAGE.md
code-of-conduct.md

update contact references

---

.dockerignore
.gitignore
.travis.yml
Makefile

add codecov

---

.travis.yml
Makefile

add quay push to travis

---

Makefile

Update binary and docker image version

---

Dockerfile
Makefile
README.md

- Update binary and docker image version
- Add quay badge
- Fix license in Dockerfile

fixlicense

---

README.md

Update slack to point to Kubernetes workspace

---

USAGE.md
code-of-conduct.md

Update slack ref in usage and code of conduct

---

internal/optimizer/ingressoptimizer.go
types/qaengine/problem.go

Fix service expose annotation

---

codecov.yml

Disable codecov changing commit status

---

README.md
USAGE.md

Updated usage instructions

---

README.md

Add codecov badge to Readme

---

.golangci.yml
internal/apiresource/deployment.go
internal/common/utils_test.go
internal/qaengine/cliengine.go
types/plan/plan_test.go

Add golangci config

---

go.mod
internal/common/utils_test.go
internal/containerizer/cnb/containerruntimeprovider_test.go
internal/containerizer/dockerfilecontainerizer_test.go
internal/containerizer/manualcontainerizer_test.go
internal/containerizer/reusecontainerizer_test.go
internal/containerizer/s2icontainerizer_test.go
internal/metadata/clustermdloader_test.go
internal/move2kube/planner_test.go
internal/source/any2kube_test.go
internal/types/ir_test.go
types/collection/cluster_test.go
types/output/helmvaluesoutput_test.go
types/plan/plan_test.go

Refactoring tests that using compression DeepEqual for better human error logging

Issue-41: Better error messages in unit tests

---

cmd/move2kube/translate.go

Fixed bug where ignoreEnv flag was getting flipped before storing.

---

internal/optimizer/imagepullpolicyoptimizer_test.go
internal/optimizer/portmergeoptimizer_test.go
internal/optimizer/replicaoptimizer_test.go

Unit tests for optimize package

---

contributing.md

Update contributing guide with signoff instructions

---

README.md
docs/README.md
docs/docker-containerization.md

Adding document guides to extend Move2Kube

---

README.md

Add link to demos repository

---

contributing.md

Add Developer certificate to contributing.md

---

Makefile

Update golanglint-ci version to 1.31

---

scripts/install.sh
scripts/installdeps.sh

Make script pass shellcheck. Avoid common bash pitfalls.

---

scripts/installdeps.sh

Only add the line to bash_profile if $PWD/bin is not already in PATH. Ask for permission before modifying bash_profile.

---

internal/metadata/clustermdloader_test.go

Add test to check if default cluster type is valid

---

internal/apiresource/networkpolicy.go
internal/apiresource/networkpolicy_test.go
internal/apiresource/testdata/networkpolicy/create-new-resources.yaml
internal/apiresourceset/tektonapiresourceset.go
internal/source/translator.go
internal/transformer/cicdtransformer.go

Fixed bug where we where merging/appending even when ther was an error. Added tests. Renamed method to be more consistent.

---

README.md

Fix codecov link

---

README.md

Fix Docker installation links

---

internal/metadata/clusters/aws-eks.yaml

Change api version in in cluster collected yaml

---

README.md

Update Readme for clarity

---

README.md

Update UI bring up instructions

---

types/plan/plan.go

Move repoinfo to end of service def in plan

---

internal/apiresourceset/tektonapiresourceset.go

Set rel path error to debug till absolute path refactoring is done

---

internal/apiresourceset/tektonapiresourceset.go

Change log level of warnings for yet to be supported tekton methods

---

internal/apiresourceset/tektonapiresourceset.go

Dont' display no git repo warning when no new containers are created

---

internal/common/utils.go

Level down warning for name corrections

---

internal/metadata/clustermdloader_test.go

complete test for checking cluster names

---

internal/metadata/testdata/qa/valid/valid.yaml
internal/metadata/testdata/qa/valid_invalid/valid.yaml

Update group in yamls

---

internal/apiresource/networkpolicy_test.go

Fixed bug where order of items in the list was changing. Now we ignore the order while comparing.

---

git-workflow.md

Added a git workflow cheatsheet.

---

git-workflow.md

Added warning about vi. Added instructions for deleting branches. Fixed typo.

---

_config.yml
index.md

Add seo gem to config

---

README.md
_config.yml

Change domain to konveyor.io

---

_config.yml

Revert home page to github.io page

---

internal/apiresource/pipeline.go
internal/apiresource/service.go
internal/customizer/customizer.go
internal/customizer/ingresscustomizer.go
internal/optimizer/ingressoptimizer.go
internal/parameterizer/ingressparameterizer.go
types/plan/plan.go

Fix ingress ports and paths

---

internal/apiresource/networkpolicy.go
internal/apiresource/service.go
internal/common/constants.go
internal/optimizer/ingressoptimizer.go
internal/types/ir.go

Fix Expose labels

---

internal/apiresource/service.go

Add exception for onlyingress in apiresource

---

internal/apiresource/pipeline.go
internal/apiresourceset/tektonapiresourceset.go

Change log messages for feature enablement logs

---

internal/parameterizer/ingressparameterizer.go

Fix ingress host variable

---

cmd/move2kube/translate.go

Add log if a plan file is detected

---

.gitignore
Gemfile.lock
_config.yml
jekyll-theme-cayman.gemspec

Fix theme name

---

internal/parameterizer/parameterizer_test.go

parameterizer basic tests -2

---

USAGE.md

Updated usage.md to point to the website instead of directly at the slack channel

---

scripts/install.sh

Fixed install script to download the new release and also use tarball instead of zip

---

scripts/install.sh

Also checks if the latest version of move2kube is installed already.

Get the latest version from GitHub and install it.

---

internal/qaengine/defaultengine.go
internal/qaengine/engine.go
internal/qaengine/engine_test.go

added AddEngine function

---

internal/apiresourceset/tektonapiresourceset.go
internal/common/sshkeys/sshkeys.go

Moved processing of known_hosts out of init.

---

internal/qaengine/defaultengine_test.go
internal/qaengine/engine_test.go

initial test for the default engine

---

_config.yml
index.md

Update homepage- added asciinema embedding and updated links

---

internal/qaengine/defaultengine.go
internal/qaengine/defaultengine_test.go
types/qaengine/problem.go

tests for other types of problems (on the default engine scenario)

---

README.md
USAGE.md

Update slack channel

---

README.md

Add ASCII cinema recording of e2e-flow sample to README.md

---

_layouts/default.html
index.md

Fix the broken links in the homepage and the footer

---

docs/install.md

Change the ordering of specified m2k installation ways

---

_includes/nav.html

Add github buttons to the website

---

internal/source/dockerfile2kube.go

fixed bug where containerization type was not being set properly.

---

internal/common/constants.go
internal/optimizer/portmergeoptimizer.go
types/qaengine/problem.go

also allow MultiSelect answers to be the empty slice.

add a default port if the service has no ports

---

_layouts/default.html

Add Konveyor logo hyperlink in the footer

---

index.md

Added some capitalizations

---

_includes/nav.html
_sass/layout.scss

Add a one line description of Move2Kube just below Move2Kube top left label

---

_includes/nav.html

Correct the "View on GitHub" link

---

samples/golang/main.go
samples/java-gradle/build.gradle
samples/java-maven/pom.xml
samples/nodejs/main.js
samples/php/php/index.php
samples/python/main.py
samples/ruby/app.rb
samples/ruby/views/main.erb

updated the samples to keep up with move2kube-demos

---

Dockerfile

fix bug where APPNAME was going out of scope and CMD [${APPNAME}] fails

---

types/plan/planutils.go
types/plan/planutils_test.go
types/plan/testdata/setrootdir/templatizednodejsplan.yaml

fixed bug where WritePlan was modifying the plan.

---

internal/move2kube/planner.go
types/plan/planutils.go

only show relative paths to the user during plan curation

---

internal/source/cfmanifest2kube.go

fixed integer parsing bug

---

internal/source/compose/utils.go
internal/source/compose/v1v2.go
internal/source/compose/v3.go
internal/source/compose2kube.go

previously we only allowed reuse of existing images. Now we support
building images using Dockerfiles mentioned in the compose yaml.

add containers if images need to be built while translating docker-compose

---

internal/source/compose/utils.go
internal/source/compose/v1v2.go
internal/source/compose/v3.go

Accoding to the docker compose reference:
https://docs.docker.com/compose/compose-file/#env_file
env_file can be either a string or a list of strings.
Our code was only handling list of strings.
Also fixed bug with how env vars are parsed in v1v2.

fix bug where we show an error if env_file is a string

---

docs/extending-move2kube/dockerfile-containerization.md
docs/extending-move2kube/extending-m2k.md
docs/tutorials/cloud-foundry.md
docs/tutorials/docker-compose.md

Rename the tutorials title. Add extending-move2kube page

---

.gitignore

Update gitignore with additional files

---

.gitignore

Add ignored files sites to gitignore

---

.github/workflows/main.yml

Add github workflow to workflows folder

---

.github/workflows/build.yml

Cleanup github actions workflow

---

.github/workflows/build.yml

Fix gomod cache in github actions

---

.github/workflows/build.yml

Add Slack notification to github actions

---

.github/workflows/build.yml
Makefile

Show commands in make and remove git actions pull request notification in slack

---

.github/workflows/build.yml

Add test coverage and upload coverage

---

.github/workflows/build.yml

Add image push and notification

---

.github/workflows/build.yml

Remove versioned image push of master

---

.github/workflows/build.yml

Fix slack message

---

.github/workflows/build.yml
.github/workflows/prbuild.yml

Create separate PR build process

---

.github/workflows/build.yml

Add notification on build failure in master

---

.github/workflows/release.yml

Add image build and push for tagging

---

.github/workflows/build.yml
.github/workflows/prbuild.yml

Give unique names to builds

---

.github/workflows/build.yml
.github/workflows/prbuild.yml

Speed up image build by pulling latest move2kube image

---

Makefile

fixed bug where build metadata was not being set properly in Makefile during builds.

---

internal/apiresource/service.go
internal/apiresourceset/k8sapiresourceset.go
internal/containerizer/cnbcontainerizer.go
internal/containerizer/containerizer.go
internal/containerizer/dockerfilecontainerizer.go
internal/containerizer/reusedockerfilecontainerizer.go
internal/containerizer/s2icontainerizer.go
internal/source/any2kube.go
internal/source/cfmanifest2kube.go
internal/source/compose/utils.go
internal/source/compose/v1v2.go
internal/source/compose/v3.go
internal/source/compose2kube.go
internal/source/dockerfile2kube.go
internal/source/testdata/datafortestingtranslate/expectedirfornodejsapp.yaml
internal/types/ir.go

add support for port forwarding while creating k8s services

---

.github/workflows/build.yml
.github/workflows/release.yml
Makefile

Add release builder and cache builder image too

---

.github/workflows/build.yml
.github/workflows/release.yml
README.md

- Dont fail build if docker image cache pull fails
- Add Github actions badge

dontfailoncache

---

internal/apiresource/service.go
internal/collector/imagescollector.go
internal/common/sshkeys/sshkeys.go
internal/optimizer/portmergeoptimizer.go
internal/qaengine/cliengine.go
internal/qaengine/httprestengine.go
internal/source/compose/v1v2.go
internal/source/compose/v3.go
types/qaengine/problem.go

fix bug where ssh key directory was not being set. change all casting to use the spf13/cast library for consistency

---

.github/workflows/build.yml
Makefile
README.md
USAGE.md

- Change website to konveyor.io
- Trigger move2kube-api build on move2kube image push

triggerapibuild

---

.github/workflows/tag.yml

Add github action to trigger tagging across repositories

---

.github/workflows/build.yml
.github/workflows/release.yml
.github/workflows/tag.yml

Add move2kube-tests based test for image before pushing

---

.github/workflows/build.yml
.github/workflows/release.yml

Add move2kube-tests to release too

---

.github/workflows/build.yml

Push image after deleting to avoid latest deletion

---

.github/workflows/release.yml

Trigger operator release

---

types/plan/planutils.go

change how we detect a m2k assets path

---

internal/optimizer/ingressoptimizer.go
internal/optimizer/portmergeoptimizer.go

fix bug where port merge optimizer was not forwarding the port from the k8s service to the k8s pod

---

go.mod
go.sum
internal/apiresource/apiresource.go
internal/apiresource/deployment.go
internal/apiresource/eventlistener.go
internal/apiresource/imagestream.go
internal/apiresource/knativeservice.go
internal/apiresource/networkpolicy.go
internal/apiresource/networkpolicy_test.go
internal/apiresource/pipeline.go
internal/apiresource/role.go
internal/apiresource/rolebinding.go
internal/apiresource/service.go
internal/apiresource/serviceaccount.go
internal/apiresource/storage.go
internal/apiresource/triggerbinding.go
internal/apiresource/triggertemplate.go
internal/apiresourceset/k8sapiresourceset.go
internal/apiresourceset/knativeapiresourceset.go

upgrade to openshift api 4.6 and fix domain name and path in routes

---

internal/source/cfmanifest2kube.go

add irContainer ports to the service only if the cf app has no ports

---

.github/workflows/assignproject.yml

Add issues to project as soon as it is created

---

internal/containerizer/cnb/containerruntimeprovider.go
internal/containerizer/cnb/dockerapiprovider_test.go

- Remove docker cli dependency
- Add test for docker api based provider

addtestfordockerapi

---

docs/tutorials/ui-local-workflow.md

Rename the UI tutorial

---

Dockerfile
internal/containerizer/cnb/dockerapiprovider.go

- Clean up docker pull log message
- Fix docker in docker usecase by copying data into containers
- Remove kubectl and pack from dockerimage

Fix docker in docker flow

---

cmd/move2kube/translate.go
internal/move2kube/planner.go

better error message when we don't find any services

---

.github/workflows/release.yml
.github/workflows/tag.yml
.grenrc.js
Makefile
scripts/builddist.go

feat: add support for automatic creation of release notes

---

.github/workflows/tag.yml

fix: personal access token name

---

.github/workflows/release.yml

fix: give gren the tag and also update the upload assets action to a working version

---

.github/workflows/release.yml
.grenrc.js

fix: calculation of tag and update the template for creating release

---

.github/workflows/assignproject.yml
.github/workflows/release.yml

fix: the triggering of releases in other repos

---

.github/workflows/assignproject.yml
.github/workflows/release.yml

fix: create temporary image so we can run move2kube-tests

---

.github/workflows/build.yml
.github/workflows/prbuild.yml
.github/workflows/release.yml
.github/workflows/tag.yml
Dockerfile
Makefile

fix: use an action to get the go version instead of hardcoding it

---

.github/workflows/publish.yml

feat: add publish release draft workflow

---

.github/workflows/build.yml
.github/workflows/prbuild.yml
README.md
contributing.md
docs/docker-containerization.md
git-workflow.md
internal/apiresource/pipeline.go

chore: Change default branch to main

---

docs/extending-move2kube/dockerfile-containerization.md
docs/installation/command-line-tool.md
docs/tutorials/cloud-foundry.md
docs/tutorials/docker-compose.md
docs/tutorials/language-platforms.md
docs/tutorials/ui-local-workflow.md
index.md

chore: Change default branch to main in docs

---

.grenrc.js

chore: add each valid PR type to a group in release notes

---

.github/workflows/release.yml

chore: release the plugin when we make a non prerelease

---

.github/workflows/labelpr.yml
.github/workflows/release.yml
.github/workflows/tag.yml
contributing.md

fix: the createRef function takes a string for the SHA so we need double quotes

---

.github/workflows/build.yml
.github/workflows/prbuild.yml
Makefile

chore: workflow changes to accomodate the new release branches

---

.gitignore

fix: do not ignore the lock files. they are supposed to be checked in. ignore vscode related stuff

---

Makefile

revert: Delta builds not working with make build

---

internal/source/cfmanifest2kube.go

fix: Fix path computation when cf manifest has a path

---

README.md

docs: Update install instructions

---

docs/installation/web-interface.md

Fix: https://github.com/konveyor/move2kube/issues/347 

fix: Mention about changing the directory to move2kube-ui

---

README.md

docs: Point usage links to website

---

cmd/move2kube/translate.go

feat: Make option for using default answers visible in help

---

.github/workflows/publish.yml

Also trigger the workflow
to update release info.

ci: change publish workflow to handle the data sent from the UI

---

.github/workflows/assignproject.yml
.github/workflows/build.yml
.github/workflows/prbuild.yml
.github/workflows/release.yml
.github/workflows/tag.yml

ci: clean up workflows to work together across multiple repos

---

Dockerfile

fix: Change default dir for image to workspace

---

.github/workflows/release.yml
README.md

docs: Add doc for all-in-one container based ui bring up

---

docs/installation/web-interface.md

docs: Add doc for all-in-one container bringup

---

Dockerfile
scripts/installdeps.sh

feat: Change base image to fedora

---

Dockerfile

fix: Optimize docker image size by cleaning up each layer

---

Dockerfile
containerconfig/containers.conf
containerconfig/storage.conf
internal/containerizer/cnb/containerruntimeprovider.go
internal/containerizer/cnb/dockerapiprovider.go
internal/containerizer/cnb/dockerapiprovider_test.go

feat: Support CNB without mounting docker sock using podman

---

containerconfig/storage.conf

fix: Add support for older kernels which does not support metacopy flag in mount

---

.github/workflows/build.yml
.github/workflows/release.yml

ci: minor fixes to allow release

---

assets/ts/internalpages/releaseui.ts

ci: change url to the permalink

---

docs/installation/command-line-tool.md

chore: add brew install instructions

---

scripts/install.sh

chore: use releaseinfo.json to get the latest stable release

---

scripts/install.sh

chore: add kubectl plugins to the install script

---

.github/workflows/releaseinfo.yml

ci: update index.yaml for helm charts during publish

---

index.yaml

ci: add index.yaml for the helm repo

---

index.yaml

ci: update index.yaml after fixing bug in move2kube-operator

---

.github/workflows/publish.yml
.github/workflows/release.yml

ci: fix bug in release workflow and add steps to publish homebrew formula

---

internal/apiresource/apiresource.go
internal/apiresource/apiresource_test.go
internal/apiresource/deployment.go
internal/apiresourceset/cicdapiresourceset.go
internal/apiresourceset/k8sapiresourceset.go
internal/apiresourceset/knativeapiresourceset.go
internal/apiresourceset/tektonapiresourceset.go
internal/common/utils.go

fixes #288
Also fixed field name in Deployment

fix: merge objects using strategic merge patch similar to kustomize and kubectl apply

---

cmd/kubectltranslate/kubectltranslate.go
cmd/move2kube/plan.go
cmd/move2kube/translate.go
internal/containerizer/containerizer.go
internal/move2kube/planner.go
internal/move2kube/planner_test.go
internal/move2kube/translator.go
internal/optimizer/optimizer.go
internal/source/any2kube.go
internal/source/any2kube_test.go
internal/source/cfmanifest2kube.go
internal/source/translator.go
types/qaengine/cache.go

feat: Initialize only containerizers of interest

---

internal/apiresource/role.go
internal/collector/cfappscollector.go
internal/collector/cfcontainertypescollector.go
internal/containerizer/cnb/containerruntimeprovider.go
internal/containerizer/cnb/dockerapiprovider.go
internal/containerizer/cnb/dockerapiprovider_test.go
internal/containerizer/cnbcontainerizer.go
internal/containerizer/containerizer.go
internal/customizer/registrycustomizer.go
internal/customizer/storagecustomizer.go
internal/parameterizer/parameterizer_test.go
internal/transformer/knativetransformer.go
types/collection/cluster.go

chore: minor refactor

---

.github/workflows/build.yml
.github/workflows/prbuild.yml
.github/workflows/release.yml
Dockerfile
Makefile
scripts/install.sh

feat: compress binaries

---

Makefile
internal/optimizer/portmergeoptimizer.go

fix: Remove per-service port question

---

cmd/common/utils.go
cmd/kubectltranslate/kubectltranslate.go
cmd/move2kube/translate.go
internal/move2kube/translator.go

fix: output path should use the name in the plan file if it exists

---

cmd/common/utils.go
cmd/move2kube/translate.go
internal/common/utils.go
internal/common/utils_test.go

feat: source and output paths should not be parent directories of the current working directory

---

internal/qaengine/cliengine.go
internal/qaengine/defaultengine.go
internal/qaengine/engine.go
internal/qaengine/httprestengine.go
internal/qaengine/storeengine.go

fix: stage 2 of select type problem not being asked

---

.github/workflows/publish.yml

chore: octokit is not defined in github workflows, use github instead

---

internal/common/constants.go
types/qaengine/config.go

feat: support * as a match all selector in qa keys

---

cmd/common/utils.go
cmd/kubectltranslate/kubectltranslate.go
cmd/move2kube/translate.go
internal/apiresourceset/tektonapiresourceset.go
internal/common/sshkeys/sshkeys.go
internal/common/utils.go
internal/common/utils_test.go
internal/customizer/storagecustomizer.go
internal/move2kube/planner.go
internal/optimizer/ingressoptimizer.go
internal/qaengine/engine.go
types/qaengine/config.go

fix: parsing of config strings

---

internal/apiresourceset/tektonapiresourceset.go
internal/common/sshkeys/sshkeys.go
internal/customizer/ingresscustomizer.go
internal/customizer/registrycustomizer.go
internal/customizer/storagecustomizer.go
internal/move2kube/planner.go
internal/optimizer/ingressoptimizer.go
internal/qaengine/defaultengine_test.go
internal/qaengine/engine.go
internal/qaengine/storeengine_test.go

chore: combine all 3 steps of asking a question into a single function call

---

.github/workflows/releaseinfo.yml

chore: get the new index.yaml from the latest release

---

internal/containerizer/containerizer.go
internal/containerizer/containerizer_test.go
internal/move2kube/planner.go

feat: order containerization options in terms of container build type priority

---

scripts/install.sh

chore: allow install script to install any tag

---

internal/transformer/cicdtransformer.go

fix: Use constructor for buildconfig transformer

---

cmd/common/version.go
cmd/kubectltranslate/kubectltranslate.go
cmd/move2kube/move2kube.go

feat: add version subcommand to translate plugin

---

docs/installation/command-line-tool.md
index.md

chore: update installation commands on the website

---

README.md
_includes/head_custom.html
_layouts/default.html
index.md

fix: Update the broken links and fix Asciinema player

---

.github/workflows/release.yml

chore: build plugin on every release but push to krew only on stable releases

---

.prettierrc
assets/ts/internalpages/releaseui.ts

chore: Github changed API token format. change our validation

---

.dockerignore

fix: the build in the dockerfile was dirty because some folders were not copied over

---

Gemfile
Gemfile.lock
_config.yml
_includes/head.html
_layouts/default.html

chore: replace google analytics tag with new google tag manager

---

internal/common/constants.go
internal/transformer/k8stransformer.go

fix: helm chart folder name should be same as the chart name

---

internal/transformer/templates/DeployHelm.sh
internal/transformer/templates/constants.go

fix: Update helm install command with new path

---

internal/transformer/k8stransformer.go

fix: the operator was using the wrong helm chart path

---

internal/starlark/testdata/transforms/t1.star
internal/starlark/testdata/transforms/t2.star

chore: add default answer to the starlark tests

---

internal/qaengine/httprestengine.go

fix: return when encountering an error while processing the API request

---

types/qaengine/problem.go

fix: accept []interface{} in addition to []string

---

docs/installation/install.md

fix: Fix web ui bring up link in installation page

---

docs/installation/web-interface.md

chore: fix command to work in Powershell for users who don't have WSL installed

---

internal/apiresource/apiresource.go
internal/apiresource/apiresource_test.go
internal/apiresource/deployment.go
internal/apiresource/networkpolicy_test.go
internal/apiresource/storage.go
internal/containerizer/cnbcontainerizer.go
internal/containerizer/containerizer_test.go
internal/containerizer/dockerfilecontainerizer.go
internal/containerizer/dockerfilecontainerizer_test.go
internal/containerizer/manualcontainerizer.go
internal/containerizer/reusecontainerizer.go
internal/containerizer/reusedockerfilecontainerizer.go
internal/containerizer/s2icontainerizer.go

fix: the target path was not being computed correctly

---

_layouts/default.html

fix: Update Move2Kube YouTube playlist link

---

types/plan/planutils.go

The values of a slice can be addressed and SetString directly
but keys and values of maps cannot be addressed in Golang.
Fix is to SetMapIndex on the map itself instead of on the value.

fix: the case of SetString on values of map[string]string

---

docs/installation/web-interface.md

fix: Update Move2Kube UI installation instructions

---

environment/container/dockerengine.go
environment/container/utils.go
environment/environment.go
environment/peercontainer.go
internal/transformer/classes/analysers/cnbcontainerizer.go
internal/transformer/classes/external/simpleexecutable.go
internal/transformer/transformer.go
types/transformer/pathmapping.go

feat: Add support for transform as executable

---

_data/releaseinfo.json

chore: v is missing from the link

---

cmd/move2kube/transform.go

feat: Suggest transform command when translate is used

---

filesystem/delta.go
filesystem/merger.go
filesystem/processor.go
filesystem/replicator.go
filesystem/utils.go

fix: set modified timestamp during filecopy to prevent repeated copy

---

assets/filepermissions.yaml
internal/transformer/transformer.go

feat: Add default ignore list for directory names

---

internal/transformer/classes/analysers/eurekareplaceengine.go
internal/transformer/classes/analysers/springbootanalyser.go

fix: Fix and cleanup eureka and springboot transforms

---

internal/transformer/classes/analysers/eurekareplaceengine.go
internal/transformer/classes/analysers/springbootanalyser.go
internal/transformer/classes/generators/buildconfiggenerator.go
internal/transformer/classes/generators/composegenerator.go
internal/transformer/classes/generators/knativegenerator.go
internal/transformer/classes/generators/kubernetesgenerator.go
internal/transformer/classes/generators/tektongenerator.go
internal/transformer/processors.go
internal/transformer/servicenamer.go
internal/transformer/transformer.go
internal/transformer/utils.go
types/ir/ir.go
types/plan/plan.go
types/source/maven/pom.go

refactor: minor changes to code style

---

assets/filepermissions.yaml
assets/inbuilt/transformers/dockerfile/dockerfiledetector/dockerfiledetector.yaml
assets/inbuilt/transformers/dockerfile/dockerimagebuildscript/docckerfilebuildscriptgenerator.yaml
assets/inbuilt/transformers/dockerfile/dockerimagebuildscript/templates/builddockerimages.bat
assets/inbuilt/transformers/dockerfile/dockerimagebuildscript/templates/builddockerimages.sh
assets/inbuilt/transformers/s2i/nodejs/nodejs.star
environment/environment.go
internal/transformer/classes/analysers/cnbcontainerizer.go
internal/transformer/classes/analysers/dockerfileanalyser.go
internal/transformer/classes/external/starlark.go
internal/transformer/classes/generators/containerimagepushscript.go
internal/transformer/classes/generators/dockerfilebuildscriptgenerator.go
internal/transformer/classes/generators/readmegenerator.go
internal/transformer/classes/generators/s2igenerator.go
internal/transformer/transformer.go
types/transformer/artifacts/dockerimagebuildscript.go

feat: Added support for existing dockerfile detector

---

environment/container/container.go
environment/container/dockerengine.go
environment/environment.go
internal/common/constants.go
internal/transformer/classes/analysers/cnbcontainerizer.go
internal/transformer/classes/generators/containerimagepushscript.go
internal/transformer/classes/generators/dockerfilebuildscriptgenerator.go
internal/transformer/classes/generators/readmegenerator.go
internal/transformer/transformer.go
types/transformer/artifacts/dockerimagebuildscript.go
types/transformer/errors.go

feat: Make transformers that require containers disabled by default

---

internal/transformer/servicenamer.go
types/source/maven/pom.go

feat: Use names of known services to guess names of unknown services using project paths

---

api/planner.go
cmd/move2kube/plan.go
cmd/move2kube/transform.go
environment/environment.go
environment/local.go
environment/peercontainer.go
internal/transformer/classes/analysers/cnbcontainerizer.go
internal/transformer/classes/external/simpleexecutable.go
internal/transformer/classes/generators/dockerfilebuildscriptgenerator.go
internal/transformer/transformer.go

feat: Add support for references to output files in artifacts

---

internal/common/utils.go
internal/transformer/classes/analysers/cnbcontainerizer.go
internal/transformer/classes/analysers/dockerfileanalyser.go
internal/transformer/classes/generators/cnbgenerator.go
internal/transformer/classes/generators/s2igenerator.go

fix: Make only lower case container image names

---

assets/inbuilt/transformers/generators/containerimagespushscript/containerimagespushscript.yaml
assets/inbuilt/transformers/generators/readmegenerator/readmegenerator.yaml
internal/common/deepcopy/merge.go
internal/transformer/classes/analysers/dockerfileanalyser.go
internal/transformer/classes/generators/cnbgenerator.go
internal/transformer/classes/generators/containerimagespushscript.go
internal/transformer/classes/generators/dockerfilebuildscriptgenerator.go
internal/transformer/classes/generators/s2igenerator.go
types/transformer/artifact.go
types/transformer/artifacts/newimages.go

fix: Merge artifacts of same type before usage

---

index.yaml

fix: updated the Chart.yaml with v0.2.0 instead of 0.2.0 and that changed the hash

---

cmd/common/utils.go
cmd/move2kube/transform.go
internal/irpreprocessor/ingresspreprocessor.go
internal/transformer/classes/generators/kubernetesgenerator.go

feat: Add IR preprocessors and allow configuration of qa cache and config files

---

api/planner.go
cmd/common/utils.go
cmd/move2kube/parameterize.go
cmd/move2kube/plan.go
cmd/move2kube/transform.go
internal/common/utils.go
types/plan/plan.go

- refactor: Change configurations flag to customizations to avoid confusion with config

refactor: Change configurations flag to customizations to avoid confusion with config

---

Makefile
assets/inbuilt/transformers/dockerfile/dockerimagebuildscript/templates/builddockerimages.bat
assets/inbuilt/transformers/dockerfile/dockerimagebuildscript/templates/builddockerimages.sh
assets/inbuilt/transformers/generators/containerimagesbuildscript/templates/buildimages.bat
assets/inbuilt/transformers/generators/containerimagesbuildscript/templates/buildimages.sh
internal/transformer/classes/generators/containerimagesbuildscript.go
internal/transformer/classes/generators/dockerfilebuildscriptgenerator.go

feat: Add support for windows and ARM

---

assets/filepermissions.yaml
assets/inbuilt/transformers/dockerfile/django/django.yaml
assets/inbuilt/transformers/dockerfile/dockerimagebuildscript/templates/builddockerimages.bat
assets/inbuilt/transformers/dockerfile/golang/golang.yaml
assets/inbuilt/transformers/dockerfile/java-war-jboss/java-war-jboss.yaml
assets/inbuilt/transformers/dockerfile/java-war-liberty/java-war-liberty.yaml
assets/inbuilt/transformers/dockerfile/java-war-tomcat/java-war-tomcat.yaml
assets/inbuilt/transformers/dockerfile/javaant/javaant.yaml
assets/inbuilt/transformers/dockerfile/javagradle/javagradle.yaml
assets/inbuilt/transformers/dockerfile/javamaven/javamaven.yaml
assets/inbuilt/transformers/dockerfile/php/php.yaml
assets/inbuilt/transformers/dockerfile/python/python.yaml
assets/inbuilt/transformers/dockerfile/ruby/ruby.yaml
assets/inbuilt/transformers/dockerfile/rust/rust.yaml
assets/inbuilt/transformers/generators/containerimagesbuildscript/templates/buildimages.bat
assets/inbuilt/transformers/s2i/golang/golang.yaml
assets/inbuilt/transformers/s2i/java/java.yaml
assets/inbuilt/transformers/s2i/php/php.yaml
assets/inbuilt/transformers/s2i/python/python.yaml
assets/inbuilt/transformers/s2i/ruby/ruby.yaml
internal/common/utils.go
internal/transformer/classes/analysers/dockerfiledetector.go
internal/transformer/classes/external/simpleexecutable.go
internal/transformer/classes/external/starlark.go
internal/transformer/classes/external/types.go
types/transformer/transformer.go

feat: Add windows support

---

internal/apiresource/service.go
internal/common/constants.go
internal/irpreprocessor/irpreprocessor.go
internal/irpreprocessor/mergepreprocessor.go
internal/irpreprocessor/registrypreprocessor.go
internal/transformer/classes/analysers/dockerfileparser.go
types/qaengine/commonqa/commonqa.go

feat: Add support for windows containers

---

docs/extending-move2kube/dockerfile-containerization.md
docs/tutorials/cloud-foundry.md
docs/tutorials/language-platforms.md
docs/tutorials/ui-local-workflow.md

Fixes- https://github.com/konveyor/move2kube/issues/472

fix: Remove copysources from the documentation

---

assets/inbuilt/transformers/generators/containerimagesbuildscript/templates/buildimages.bat
assets/inbuilt/transformers/generators/containerimagesbuildscript/templates/buildimages.sh
internal/transformer/classes/generators/containerimagesbuildscript.go
internal/transformer/classes/generators/dockerfilebuildscriptgenerator.go
types/transformer/artifacts/containerimagebuildscript.go

fix: Fix build script context paths

---

cmd/move2kube/move2kube.go
cmd/move2kube/plan.go
cmd/move2kube/transform.go
environment/environment.go
environment/error.go
environment/local.go
environment/peercontainer.go
internal/common/logging.go
internal/common/utils.go
internal/transformer/classes/analysers/cnbcontainerizer.go
internal/transformer/classes/external/executable.go
internal/transformer/transformer.go
lib/planner.go
lib/transformer.go

feat: Change logging to support multiple levels; cleanup on interrupt

---

cmd/move2kube/move2kube.go
cmd/move2kube/plan.go
cmd/move2kube/transform.go

fix: Fix conflicting flags and missing cleanup at end of execution

---

internal/transformer/classes/analysers/dockerfileparser.go

fix: Resolve the windows nodeselector bug

---

docs/tutorials/cloud-foundry.md

This updates the tutorial with the new locations of the files.
Signed-off-by: JJ Asghar <jjasghar@gmail.com>
Co-authored-by: Paul Czarkowski <username.taken@gmail.com>

The v0.2.0 moved some files around

---

internal/transformer/classes/external/executable.go
internal/transformer/transformer.go
internal/transformer/utils.go
lib/planner.go
types/transformer/plan.go

feat: Automatically add path if path is missing in external transformer class

---

internal/apiresource/networkpolicy.go
internal/apiresource/testdata/networkpolicy/create-new-resources.yaml
internal/transformer/classes/analysers/compose/v1v2.go
internal/transformer/classes/analysers/compose/v3.go

fix:  Naming issues for container block and network policy labels

---

internal/transformer/classes/analysers/dockerfiledetector.go
internal/transformer/classes/analysers/dockerfileparser.go

Fixes https://github.com/konveyor/move2kube/issues/583

fix: Resolve unable to find ports in Dockerfile bug

---

internal/common/constants.go
internal/common/utils.go
internal/transformer/classes/analysers/dockerfiledetector.go
internal/transformer/transformer.go

fix: Ignore dirs during iteration in various transformers

---

internal/common/constants.go
internal/common/utils.go

fix: Fix service name renaming; Remove error on finding incorrect yamls

---

filesystem/templatecopy.go
internal/transformer/classes/external/starlark.go

fix: bug fixes to starlark readdir and template package

---

cmd/move2kube/move2kube.go
cmd/move2kube/plan.go

feat: log to a file

---

Makefile

fix: Fix tab space in Makefile for container runtime check line

---

assets/filepermissions.yaml
assets/inbuilt/transformers/dockerfile/java/maven/templates/Dockerfile.maven-build
common/constants.go
environment/environment.go
transformer/classes/dockerfile/java/jaranalyser.go
transformer/classes/dockerfile/java/mavenanalyser.go
transformer/transformer.go
types/transformer/artifacts/maven.go

feat: maven profile capturing and question during transform

---

assets/inbuilt/transformers/dockerfile/java/maven/templates/Dockerfile.maven-build
transformer/classes/dockerfile/java/mavenanalyser.go
types/source/maven/pom.go

feat: added classifier based on plugin+profile matching

---

assets/inbuilt/transformers/dockerfile/java/jar/templates/Dockerfile.embedded
transformer/classes/dockerfile/java/mavenanalyser.go
transformer/classes/dockerfile/java/springbootutils.go
types/transformer/artifacts/springboot.go

feat: Set default maven profiles based on activebydefault flag in pom

---

transformer/classes/dockerfile/java/mavenanalyser.go
transformer/classes/external/executable.go
transformer/utils.go
types/source/maven/pom.go

fix: Fix output parsing in executable transformer and fix pom parsing

---

cmd/move2kube/move2kube.go

See https://github.com/golang/go/issues/15210

fix: set umask to 0 so that file and directory permissions are set correctly

---

transformer/classes/compose/composeanalyser.go
transformer/classes/dockerfile/dotnet5dockerfilegenerator.go
transformer/classes/dockerfile/golangdockerfilegenerator.go
transformer/classes/dockerfile/java/jaranalyser.go
transformer/classes/dockerfile/nodejsdockerfilegenerator.go
transformer/classes/dockerfile/phpdockerfilegenerator.go
transformer/classes/dockerfile/utils.go
transformer/classes/dockerfile/windows/consoleappdockerfilegenerator.go
transformer/classes/dockerfile/windows/silverlightwebappdockerfilegenerator.go
transformer/classes/dockerfile/windows/webappdockerfilegenerator.go

fix: Replace "Dockerfile" string with the constant string

---

assets/inbuilt/transformers/kubernetes/kubernetes/kubernetes.yaml
assets/inbuilt/transformers/kubernetes/parameterizers/parameterizers.yaml
common/utils.go
environment/environment.go
lib/parameterizer.go
lib/testdata/parameterizers/pack.yaml
parameterizer/parameterizer.go
transformer/classes/kubernetes/kubernetesgenerator.go
transformer/classes/kubernetes/parameterizer.go
transformer/processors.go
types/parameterizer/parameterizer.go
types/transformer/pathmapping.go

feat: Enable path templates in path mappings

---

assets/inbuilt/transformers/kubernetes/parameterizers/parameterizers.yaml
environment/environment.go
filesystem/processor.go
filesystem/templatecopy.go
transformer/classes/dockerfile/dockerfileparser.go
transformer/classes/kubernetes/kubernetesgenerator.go
transformer/classes/kubernetes/parameterizer.go

feat: Expose path configurations in transformers

---

apiresource/service.go
filesystem/processor.go
filesystem/templatecopy.go
transformer/classes/kubernetes/kubernetesgenerator.go

feat: Expose helm-chart name

---

assets/inbuilt/transformers/kubernetes/parameterizers/parameterizers.yaml
transformer/classes/dockerfile/dockerfileparser.go
transformer/classes/kubernetes/kubernetesgenerator.go
transformer/classes/kubernetes/parameterizer.go

fix: Changed project name and paths to service name and paths in k8s-gen and paramaterizer

---

types/ir/ir.go

fix: fix error in IR merge

---

cmd/move2kube/transform.go
common/utils.go
environment/environment.go
filesystem/templatecopy.go
lib/planner.go
lib/utils.go
transformer/processors.go
types/transformer/pathmapping.go

feat:  CustomTemplate path mapping to switch template-delimiter

---

filesystem/templatecopy.go

feat: Added template resolution for file paths

---

apiresource/service.go
assets/inbuilt/transformers/kubernetes/kubernetes/kubernetes.yaml
common/constants.go
common/utils.go
transformer/classes/kubernetes/kubernetesgenerator.go
transformer/classes/kubernetes/parameterizer.go

feat: Make ingress name configurable in kubernetes transformer

---

transformer/classes/external/starlark.go
transformer/processors.go
types/transformer/pathmapping.go

feat: Delete path-mapping to allow for file/folder deletion

---

cmd/move2kube/move2kube.go
cmd/move2kube/umask.go

feat: Set umask only in non-windows platforms

---

assets/inbuilt/transformers/dockerfilegenerator/java/jar/templates/Dockerfile.embedded
common/constants.go
common/utils.go
transformer/dockerfilegenerator/java/jaranalyser.go
transformer/dockerfilegenerator/java/mavenanalyser.go
types/transformer/artifacts/java.go

feat: Add support for jar file containerization

---

common/utils.go
filesystem/delta.go
filesystem/merger.go
filesystem/replicator.go
filesystem/templatecopy.go
filesystem/utils.go

feat: Use streaming file copy

---

transformer/dockerfilegenerator/dotnet5dockerfiletransformer.go

fix: Updated the dotnet core versions supported by Move2Kube

---

.github/workflows/release.yml

ci: add more repos to the release workflow

---

assets/js/internalpages/releaseui-bundle.js
package.json

ci: fix the shell command that does the bundling

---

common/constants.go
qaengine/engine.go
transformer/transformer.go
types/qaengine/problem.go

feat: Add support for silent questions which are set only from config

---

assets/filepermissions.yaml
assets/inbuilt/transformers/dockerfilegenerator/java/tomcat/templates/Dockerfile.tomcat
assets/inbuilt/transformers/dockerfilegenerator/java/tomcat/tomcat.yaml
assets/inbuilt/transformers/dockerfilegenerator/java/waranalyser/war.yaml
assets/inbuilt/transformers/dockerfilegenerator/java/warrouter/warrouter.yaml
lib/planner.go
qaengine/engine.go
transformer/containerizer.go
transformer/dockerfilegenerator/java/mavenanalyser.go
transformer/dockerfilegenerator/java/tomcat.go
transformer/dockerfilegenerator/java/waranalyser.go
transformer/routertransformer.go
transformer/transformer.go
types/qaengine/problem.go
types/transformer/artifacts/config.go
types/transformer/artifacts/java.go
types/transformer/artifacts/newimages.go

feat: Add support for router transformer and war file containerization

---

assets/filepermissions.yaml
assets/inbuilt/transformers/dockerfilegenerator/java/jboss/jboss.yaml
assets/inbuilt/transformers/dockerfilegenerator/java/jboss/templates/Dockerfile.jboss
assets/inbuilt/transformers/dockerfilegenerator/java/liberty/liberty.yaml
assets/inbuilt/transformers/dockerfilegenerator/java/liberty/templates/Dockerfile.liberty
transformer/dockerfilegenerator/java/jboss.go
transformer/dockerfilegenerator/java/liberty.go
transformer/routertransformer.go
transformer/transformer.go

feat: Add war support for liberty and jboss

---

assets/filepermissions.yaml
assets/inbuilt/transformers/dockerfilegenerator/java/earrouter/earrouter.yaml
assets/inbuilt/transformers/dockerfilegenerator/java/jboss/jboss.yaml
assets/inbuilt/transformers/dockerfilegenerator/java/liberty/liberty.yaml
assets/inbuilt/transformers/dockerfilegenerator/java/tomcat/tomcat.yaml
transformer/dockerfilegenerator/java/jaranalyser.go
transformer/dockerfilegenerator/java/jboss.go
transformer/dockerfilegenerator/java/liberty.go
transformer/dockerfilegenerator/java/mavenanalyser.go
transformer/dockerfilegenerator/java/tomcat.go
transformer/dockerfilegenerator/java/types.go

feat: Add support for Ear

---

environment/local.go
environment/types.go
transformer/transformer.go
types/transformer/transformer.go

feat: Make isolation configurable on a per transformer basis

---

docs/installation/web-interface.md
docs/tutorials/ui-local-workflow.md

chore: update commands for v0.3 release

---

scripts/install.sh

chore: avoid github quota by using Github pages to serve releaseinfo.json

---

assets/inbuilt/transformers/dockerfilegenerator/dotnetcore/templates/Dockerfile
transformer/dockerfilegenerator/dotnetcoredockerfilegenerator.go

fix: Normalize the dotnetcore service name so that it conforms to the Kubernetes standard

---

apiresource/buildconfig.go
lib/planner.go
transformer/dockerfilegenerator/java/mavenanalyser.go
transformer/kubernetes/buildconfigtransformer.go
transformer/kubernetes/tektontransformer.go

fix: fix target cluster question not being honored

---

assets/filepermissions.yaml
assets/inbuilt/transformers/dockerfilegenerator/java/gradle/gradle.yaml
assets/inbuilt/transformers/dockerfilegenerator/java/gradle/templates/Dockerfile.gradle-build
go.mod
go.sum
transformer/dockerfilegenerator/java/gradle/constants.go
transformer/dockerfilegenerator/java/gradle/gradleparser.go
transformer/dockerfilegenerator/java/gradle/quotedRegex.go
transformer/dockerfilegenerator/java/gradle/types.go
transformer/dockerfilegenerator/java/gradleanalyser.go
transformer/dockerfilegenerator/java/mavenanalyser.go
transformer/dockerfilegenerator/java/springbootutils.go
transformer/dockerfilegenerator/java/utils.go
transformer/transformer.go
types/transformer/artifacts/config.go
types/transformer/artifacts/gradle.go
types/transformer/artifacts/maven.go
types/transformer/artifacts/springboot.go

feat: Add support for gradle based java builds

---

transformer/dockerfilegenerator/dotnetcoredockerfilegenerator.go

fix: Resolve publish profile path bug

---

transformer/transformer.go
transformer/utils.go
types/transformer/transformer.go

feat: Allow for artifact postprocessing with custom transformers

---

cmd/move2kube/plan.go
cmd/move2kube/transform.go
common/utils.go
lib/planner.go
transformer/external/starlarktransformer.go
transformer/utils.go
types/transformer/transformer.go

feat: Add support for overriding transformers in custom transformers

---

transformer/transformer.go
types/transformer/transformer.go

feat: Allow intercepting artifacts by transformers

---

transformer/transformer.go

fix: Addressed bug in transformer recursion

---

assets/inbuilt/transformers/containerimage/containerimagesbuildscript/templates/buildimages.sh
assets/inbuilt/transformers/dockerfile/dockerimagebuildscript/templates/builddockerimages.sh

fix: Added missing shebang in scripts

---

transformer/containerizer.go

fix: fix cf artifact type setting

---

assets/inbuilt/transformers/kubernetes/sourceparameterizer/parameterizers.yaml

fix: Prevent SourceParameterizer from being triggered for new apps

---

Makefile
transformer/dockerfilegenerator/java/gradle/gradleparser.go
transformer/utils.go

fix: Use go install in Makefile since go get is deprecated for binary installs

---

assets/filepermissions.yaml
assets/inbuilt/transformers/kubernetes/clusterselector/clusters/aws-eks.yaml
assets/inbuilt/transformers/kubernetes/clusterselector/clusters/azure-aks.yaml
assets/inbuilt/transformers/kubernetes/clusterselector/clusters/gcp-gke.yaml
assets/inbuilt/transformers/kubernetes/clusterselector/clusters/ibm-iks.yaml
assets/inbuilt/transformers/kubernetes/clusterselector/clusters/ibm-openshift.yaml

feat: Add support for in-built cloud specific cluster versions

---

assets/inbuilt/transformers/dockerfilegenerator/java/zuul/zuulanalyser.yaml
transformer/dockerfilegenerator/java/zuulanalyser.go

feat: Add support for zuul processor for IR

---

assets/filepermissions.yaml
assets/inbuilt/transformers/dockerfilegenerator/java/eurekareplaceengine/eureka.yaml
environment/environment.go

feat: Check and remove paths outside move2kube relevant folders in artifacts and pathmappings

---

environment/environment.go
transformer/external/starlarktransformer.go

feat: Restrict starlark file access to only move2kube relevant folders

---

cmd/move2kube/plan.go
cmd/move2kube/transform.go
cmd/move2kube/version.go
common/constants.go
environment/local.go

feat: Add flag to allow for disabling local file execution

---

assets/filepermissions.yaml
assets/inbuilt/presets/dc.yaml
assets/inbuilt/presets/usepodmaninscripts.yaml

feat: Add a preset to use podman in generated scripts

---

assets/inbuilt/transformers/dockerfile/dockerimagebuildscript/templates/builddockerimages.bat
assets/inbuilt/transformers/dockerfile/dockerimagebuildscript/templates/builddockerimages.sh

feat: check the directory the script is being run from and give a warning

---

lib/planner.go
transformer/cloudfoundrytransformer.go
transformer/compose/composeanalyser.go
transformer/containerizer.go
transformer/servicenamer.go
transformer/transformer.go
transformer/utils.go
types/plan/plan.go

feat: Use transformerName to denote processing transformer for each service in plan

---

assets/filepermissions.yaml
assets/inbuilt/transformers/kubernetes/parameterizer/config/replicas.yaml

feat: Add replicas parameterization as default parameterization

---

.github/workflows/release.yml

chore: remove reference to personal repos/forks

---

transformer/kubernetes/apiresource/buildconfig.go

chore: remove personal names and references

---

transformer/containerizer.go

fix: Fix support for containerization in cloud foundry

---

collector/cfappscollector.go
common/utils.go
transformer/cloudfoundrytransformer.go
types/collection/cfapps.go

fix: Format the interfaces in map values as json

---

transformer/cloudfoundrytransformer.go

fix: fix usage of docker image in cloud foundry

---

assets/inbuilt/transformers/compose/composeanalyser/composeanalyser.yaml
transformer/compose/composeanalyser.go
transformer/compose/v1v2.go
transformer/compose/v3.go
transformer/dockerfile/dockerfilebuildscripttransformer.go
transformer/kubernetes/apiresource/pipeline.go
types/ir/ir.go
types/transformer/artifacts/dockerfileartifact.go

feat: Add support for building dockerfile in compose

---

transformer/cloudfoundrytransformer.go
types/collection/cfapps.go

fix: fix error when VCAP is empty in collect

---

transformer/dockerfile/dockerfileparsertransformer.go
transformer/kubernetes/apiresource/pipeline.go

fix: fix dockerfilepath and contextpath in dockerfileparser

---

transformer/cloudfoundrytransformer.go
transformer/dockerfile/dockerfileparsertransformer.go
transformer/dockerfilegenerator/java/springbootutils.go
types/ir/ir.go

fix: fix strategic patch commit of podspec in ir

---

transformer/dockerfilegenerator/java/gradle/gradleparser.go

fix: remove incorrect info log in gradle parser

---

assets/inbuilt/transformers/kubernetes/parameterizer/parameterizer.yaml
common/constants.go
common/globals.go
common/pathsofinterest.go
common/utils.go
lib/planner.go
qaengine/defaultengine_test.go
transformer/compose/v1v2.go
transformer/compose/v3.go
transformer/containerimage/containerimagespushscripttransformer.go
transformer/dockerfilegenerator/dotnetcoredockerfilegenerator.go
transformer/kubernetes/apiresource/storage.go
transformer/kubernetes/apiresource/triggertemplate.go
transformer/kubernetes/irpreprocessor/registrypreprocessor.go
transformer/kubernetes/parameterizer/parameterizer.go
transformer/kubernetes/parameterizer/types.go
transformer/kubernetes/parameterizertransformer.go
types/qaengine/commonqa/commonqa.go

fix: Fix error when username/password is entered for registry auth

---

cmd/commands/flags.go
cmd/commands/plan.go
cmd/commands/transform.go
cmd/commands/utils.go
qaengine/cliengine.go
qaengine/engine.go
qaengine/storeengine.go
qaengine/storeengine_test.go
transformer/kubernetes/irpreprocessor/registrypreprocessor.go
types/qaengine/cache.go
types/qaengine/cache_test.go
types/qaengine/config.go

feat: Allow password persistence with flag and prevent password question repetition

---

transformer/containerizer.go

feat: Choose containerization option which matches servicename in cf if available

---

assets/filepermissions.yaml
assets/inbuilt/transformers/dockerfilegenerator/java/earanalyser/ear.yaml
assets/inbuilt/transformers/dockerfilegenerator/java/gradle/gradle.yaml
assets/inbuilt/transformers/dockerfilegenerator/java/gradle/templates/Dockerfile.gradle-build
assets/inbuilt/transformers/dockerfilegenerator/java/jar/jar.yaml
assets/inbuilt/transformers/dockerfilegenerator/java/jboss/jboss.yaml
assets/inbuilt/transformers/dockerfilegenerator/java/jboss/templates/Dockerfile.jboss
assets/inbuilt/transformers/dockerfilegenerator/java/liberty/liberty.yaml
assets/inbuilt/transformers/dockerfilegenerator/java/liberty/mappings/javalibertyimagemappings.yaml
assets/inbuilt/transformers/dockerfilegenerator/java/liberty/templates/Dockerfile.liberty
assets/inbuilt/transformers/dockerfilegenerator/java/mappings/javapackageversions.yaml
assets/inbuilt/transformers/dockerfilegenerator/java/maven/maven.yaml
assets/inbuilt/transformers/dockerfilegenerator/java/maven/templates/Dockerfile.maven-build
assets/inbuilt/transformers/dockerfilegenerator/java/tomcat/templates/Dockerfile.tomcat
assets/inbuilt/transformers/dockerfilegenerator/java/tomcat/tomcat.yaml
assets/inbuilt/transformers/dockerfilegenerator/java/waranalyser/war.yaml
transformer/dockerfilegenerator/java/earanalyser.go
transformer/dockerfilegenerator/java/gradle/gradleparser.go
transformer/dockerfilegenerator/java/gradle/types.go
transformer/dockerfilegenerator/java/gradleanalyser.go
transformer/dockerfilegenerator/java/jaranalyser.go
transformer/dockerfilegenerator/java/jboss.go
transformer/dockerfilegenerator/java/liberty.go
transformer/dockerfilegenerator/java/mavenanalyser.go
transformer/dockerfilegenerator/java/tomcat.go
transformer/dockerfilegenerator/java/utils.go
transformer/dockerfilegenerator/java/waranalyser.go
types/transformer/artifacts/gradle.go

feat: Add more gradle property extraction capabilities

---

README.md

fix: fix broken links in readme

---

assets/filepermissions.yaml
assets/inbuilt/transformers/dockerfilegenerator/java/tomcat/templates/Dockerfile.tomcat

fix: Update the download link of Tomcat in Dockerfile template

---

assets/inbuilt/transformers/dockerfilegenerator/windows/winconsole/templates/Dockerfile
assets/inbuilt/transformers/dockerfilegenerator/windows/winsilverlightweb/templates/Dockerfile
assets/inbuilt/transformers/dockerfilegenerator/windows/winweb/templates/Dockerfile
transformer/dockerfilegenerator/windows/utils.go

fix: Bug fixes for windows containerization

---

transformer/external/starlarktransformer.go

feat: Exposed temp path in starlark transformer

---

collector/cfappscollector.go
collector/cfservicescollector.go

feat: Added name to the metadata of the cf collect

---

transformer/cloudfoundrytransformer.go

fix: prevent cf transformer creation of ir when containerizing app

---

transformer/cloudfoundrytransformer.go

fix: remove assumption of port 8080 for cf apps when no port is found

---

cmd/transform.go
lib/planner.go
lib/transformer.go
transformer/containerizer.go
transformer/routertransformer.go
transformer/transformer.go
types/plan/plan.go

feat: sort transformers to ensure order of execution

---

lib/transformer.go

fix: fix transformers warning

---

assets/built-in/transformers/dockerfilegenerator/java/gradle/templates/Dockerfile.gradle-build
assets/built-in/transformers/dockerfilegenerator/java/maven/templates/Dockerfile.maven-build
transformer/dockerfilegenerator/java/gradleanalyser.go
transformer/dockerfilegenerator/java/mavenanalyser.go
types/transformer/artifacts/maven.go

feat: Add support for mvnw

---

.github/workflows/publish.yml

chore: now website will trigger homebrew after updating releaseinfo.json

---

cmd/transform.go

fix: warn when plan is present and source or customization is specified

---

transformer/dockerfilegenerator/java/mavenanalyser.go

fix: bug where finalName in Maven profiles was not being used

---

transformer/kubernetes/apiresource/deployment.go

feat: prioritize deployment over deploymentconfig if both are supported by a cluster

---

assets/built-in/presets/containerizeonly.yaml
assets/built-in/transformers/containerimagespushscript/transformer.yaml
assets/built-in/transformers/dockerfile/dockerimagebuildscript/transformer.yaml
assets/filepermissions.yaml

feat: Add support for containerize only preset

---

common/constants.go
transformer/dockerfilegenerator/java/zuulanalyser.go
transformer/kubernetes/apiresource/service.go
transformer/kubernetes/irpreprocessor/ingresspreprocessor.go
transformer/kubernetes/irpreprocessor/mergepreprocessor.go

feat: Allow clusterip only service

---

transformer/kubernetes/apiresource/service.go
transformer/kubernetes/irpreprocessor/ingresspreprocessor.go
types/ir/ir.go

feat: Split Service option question into two

---

.github/workflows/e2etest.yml

feat: trigger end to end test in move2kube-tests repo for transforming and deploying language platforms in a cluster

---

environment/container/container.go
environment/container/dockerengine.go
environment/container/fileinfo.go
environment/environment.go
environment/local.go
environment/peercontainer.go

fix: fix containerized transformer path mapping

---

transformer/dockerfilegenerator/java/gradle/types.go

fix: Fix panic error in gradle transformer

---

transformer/compose/v1v2.go
transformer/compose/v3.go

fix: fix container name being empty in compose

---

transformer/kubernetes/apiresource/service.go
transformer/kubernetes/tektontransformer.go

fix: fix tekton ingress creation

---

scripts/install.sh

fix: check if sudo is installed in the install script

---

transformer/dockerfilegenerator/dotnetcoredockerfilegenerator.go
transformer/dockerfilegenerator/windows/consoleappdockerfilegenerator.go
transformer/dockerfilegenerator/windows/silverlightwebappdockerfilegenerator.go
transformer/dockerfilegenerator/windows/webappdockerfilegenerator.go
types/source/dotnet/csproj.go

chore: change the warning messages to give path to the csproj file that failed version check

---

common/utils.go
transformer/dockerfilegenerator/java/springbootutils.go

fix: warnings when trying to get files from non existent directory src/main/resources

---

assets/built-in/transformers/dockerfilegenerator/java/maven/templates/Dockerfile.maven-build

fix: Update the template to skip the checkstyle validation

---

transformer/dockerfilegenerator/java/gradleanalyser.go

fix: gradle artifact name is wrong on spring pet-clinic sample app

---

transformer/external/starlarktransformer.go

fix: Query output for multi-select marshalling crash addressed

---

.github/workflows/e2etest.yml

feat: add another e2e test for move2kube CLI with enterprise app

---

transformer/servicenamer.go

fix: Normalize the git repo name for the service name

---

common/utils.go
transformer/dockerfilegenerator/java/gradleanalyser.go
transformer/dockerfilegenerator/java/mavenanalyser.go
transformer/dockerfilegenerator/java/springbootutils.go

fix: detection of port not working for spring boot application.yaml

---

transformer/dockerfilegenerator/java/mavenanalyser.go

fix: warning about service directory path even when it's not a spring boot app

---

transformer/dockerfilegenerator/java/mavenanalyser.go
types/transformer/artifacts/java.go

fix: check the parent poms as well in a multi-module project to find spring boot dependencies

---

transformer/kubernetes/parameterizer/parameterizer.go

fix: parameters in parameterizer templates were not being filled in with the correct values

---

assets/built-in/transformers/kubernetes/parameterizer/transformer.yaml
transformer/kubernetes/parameterizer/parameterizer.go
transformer/kubernetes/parameterizer/parameterizer_test.go
transformer/kubernetes/parameterizertransformer.go

fix: allow specifying the environments to parameterize for

---

assets/built-in/transformers/dockerfile/dockerimagebuildscript/templates/builddockerimages.bat
assets/built-in/transformers/dockerfile/dockerimagebuildscript/templates/builddockerimages.sh
assets/built-in/transformers/dockerfilegenerator/java/mappings/javapackageversions.yaml
transformer/dockerfilegenerator/java/jaranalyser.go
transformer/dockerfilegenerator/java/utils.go

Also expose the service name to the Dockerfile template in JAR transformer.

fix: add java 7 and 8 to the list of supported java package versions

---

Dockerfile
Makefile
README.md
assets/built-in/transformers/dockerfilegenerator/golang/transformer.yaml
common/utils.go
go.mod
transformer/dockerfilegenerator/dotnetcoredockerfilegenerator.go
transformer/dockerfilegenerator/golangdockerfiletransformer.go
types/ir/ir.go

chore: Move to go 1.18 and use generics

---

assets/built-in/transformers/dockerfilegenerator/java/maven/templates/Dockerfile.maven-build
common/constants.go
qaengine/cliengine.go
transformer/dockerfilegenerator/java/earanalyser.go
transformer/dockerfilegenerator/java/gradleanalyser.go
transformer/dockerfilegenerator/java/jaranalyser.go
transformer/dockerfilegenerator/java/mavenanalyser.go
transformer/dockerfilegenerator/java/utils.go
transformer/dockerfilegenerator/java/waranalyser.go
types/transformer/artifacts/maven.go

feat: allow putting the build stage in the same Dockerfile as the run stage. Also allow omitting the build stage.

---

assets/built-in/presets/enablecontainerizedtransformers.yaml
assets/built-in/transformers/cnb/transformer.yaml
assets/filepermissions.yaml
common/deepcopy/deepcopy.go
transformer/cloudfoundrytransformer.go
transformer/cnbcontainerizer.go
transformer/kubernetes/apiresource/deployment.go
transformer/kubernetes/apiresource/knativeservice.go
transformer/kubernetes/clusterselector.go
transformer/kubernetes/parameterizer/parameterizer.go
transformer/kubernetes/tektontransformer.go
transformer/transformer.go
types/ir/ir.go
types/transformer/artifacts/cnb.go

feat: generic cnb containerizer

---

assets/built-in/transformers/dockerfilegenerator/java/tomcat/templates/Dockerfile.tomcat

Co-authored-by: Harikrishnan Balagopal <harikrishmenon@gmail.com>

fix: Resolve Tomcat permission denied error on Openshift cluster

---

Makefile

feat: remove the dependency on gcc/clang/ld and other C compiler and linker toolchains

---

cmd/plan.go
cmd/transform.go
common/pathsofinterest.go

fix: check properly if the default files exist and ignore if they don't

---

cmd/plan.go
cmd/transform.go
common/pathsofinterest.go
common/utils.go
scripts/generator/persistpermissions.go
transformer/dockerfilegenerator/dotnetcoredockerfilegenerator.go
transformer/dockerfilegenerator/phpdockerfiletransformer.go
transformer/dockerfilegenerator/windows/consoleappdockerfilegenerator.go
transformer/dockerfilegenerator/windows/silverlightwebappdockerfilegenerator.go
transformer/dockerfilegenerator/windows/webappdockerfilegenerator.go

fix: bug where we try to read the default config file even when it is not present

---

.github/workflows/release.yml
Dockerfile
Makefile

fix: binaries compressed for Ubuntu seg fault when run on CentOS

---

Makefile
assets/built-in/transformers/dockerfilegenerator/windows/winweb/templates/Dockerfile
common/constants.go
common/sshkeys/sshkeys.go
common/utils.go
qaengine/defaultengine_test.go
qaengine/storeengine_test.go
transformer/cloudfoundrytransformer.go
transformer/dockerfilegenerator/dotnet/constants.go
transformer/dockerfilegenerator/dotnet/utils.go
transformer/dockerfilegenerator/dotnetcoredockerfilegenerator.go
transformer/dockerfilegenerator/java/gradleanalyser.go
transformer/dockerfilegenerator/java/mavenanalyser.go
transformer/dockerfilegenerator/java/utils.go
transformer/dockerfilegenerator/phpdockerfiletransformer.go
transformer/dockerfilegenerator/pythondockerfiletransformer.go
transformer/dockerfilegenerator/windows/consoleappdockerfilegenerator.go
transformer/dockerfilegenerator/windows/silverlightwebappdockerfilegenerator.go
transformer/dockerfilegenerator/windows/utils.go
transformer/dockerfilegenerator/windows/webappdockerfilegenerator.go
transformer/external/starlarktransformer.go
transformer/kubernetes/irpreprocessor/ingresspreprocessor.go
transformer/kubernetes/parameterizer/parameterizer.go
transformer/kubernetes/tektontransformer.go
types/qaengine/commonqa/commonqa.go
types/source/dotnet/csproj.go
types/transformer/artifacts/dotnet.go

feat: allow creating one dockerfile per child project in a dot net multi-project app

---

assets/built-in/transformers/dockerfilegenerator/windows/mappings/dotnetwindowsversionmapping.yaml
assets/built-in/transformers/dockerfilegenerator/windows/winweb/templates/Dockerfile
assets/built-in/transformers/dockerfilegenerator/windows/winweb/transformer.yaml
assets/filepermissions.yaml
common/utils.go
filesystem/templatecopy.go
transformer/dockerfilegenerator/windows/types.go
transformer/dockerfilegenerator/windows/utils.go
transformer/dockerfilegenerator/windows/webappdockerfilegenerator.go

fix: the run stage of dockerfiles generated for dot net web app was using a deprecated base image

---

Makefile

refactor: support only docker for multi arch image build

---

transformer/kubernetes/clusterselector.go

fix: the default cluster name so that QA works properly

---

.github/workflows/release.yml
Dockerfile
Makefile

Please refer to: https://github.com/konveyor/move2kube-api/pull/112#issue-1303650030

fix: multi arch build with buildkit always enabled

---

.github/workflows/build.yml
.github/workflows/release.yml

fix: setup qemu and buildx to worlflows

---

transformer/dockerfilegenerator/dotnetcoredockerfilegenerator.go
transformer/dockerfilegenerator/windows/consoleappdockerfilegenerator.go
transformer/dockerfilegenerator/windows/silverlightwebappdockerfilegenerator.go
transformer/dockerfilegenerator/windows/utils.go
transformer/dockerfilegenerator/windows/webappdockerfilegenerator.go

fix: panic when target framework version is not present in a dot net c sharp project file

---

.github/workflows/build.yml

fix: identifier issue in workflow

---

transformer/dockerfilegenerator/java/jaranalyser.go

fix: ir was not being propagated through artifacts for use by downstream transformers

---

assets/built-in/transformers/dockerfilegenerator/mappings/nodeversions.yaml
assets/built-in/transformers/dockerfilegenerator/nodejs/templates/Dockerfile
assets/built-in/transformers/dockerfilegenerator/nodejs/transformer.yaml
assets/filepermissions.yaml
go.mod
go.sum
samples/nodejs/package.json
transformer/dockerfilegenerator/nodejsdockerfiletransformer.go
transformer/dockerfilegenerator/utils.go

Resolves- https://github.com/konveyor/move2kube/issues/811
Co-authored-by: Harikrishnan Balagopal <harikrishmenon@gmail.com>

feat: Add node version selection heuristic to handle conditional Node.JS version in package.json

---

assets/built-in/transformers/dockerfilegenerator/dotnetcore/templates/Dockerfile
assets/built-in/transformers/dockerfilegenerator/dotnetcore/transformer.yaml
assets/built-in/transformers/dockerfilegenerator/mappings/nodeversions.yaml
assets/built-in/transformers/dockerfilegenerator/nodejs/templates/Dockerfile
common/utils.go
transformer/dockerfilegenerator/dotnetcoredockerfilegenerator.go
transformer/dockerfilegenerator/nodejsdockerfiletransformer.go
transformer/routertransformer.go

fix: detect the node version from the package.json in the dot net core transformer instead of hard coding

---

transformer/dockerfilegenerator/java/mavenanalyser.go

chore: capitalize the start of a sentence in a question.

---

transformer/dockerfilegenerator/dotnetcoredockerfilegenerator.go
types/qaengine/config.go

fix: quote the sub keys that come from user provided data since they can contain special characters

---

common/utils.go
transformer/dockerfile/dockerfileparsertransformer.go
transformer/dockerfilegenerator/dotnetcoredockerfilegenerator.go
transformer/dockerfilegenerator/java/earanalyser.go
transformer/dockerfilegenerator/java/gradleanalyser.go
transformer/dockerfilegenerator/java/jaranalyser.go
transformer/dockerfilegenerator/java/jboss.go
transformer/dockerfilegenerator/java/liberty.go
transformer/dockerfilegenerator/java/mavenanalyser.go
transformer/dockerfilegenerator/java/tomcat.go
transformer/dockerfilegenerator/java/waranalyser.go
transformer/dockerfilegenerator/nodejsdockerfiletransformer.go
transformer/dockerfilegenerator/windows/webappdockerfilegenerator.go

fix: normalize the service and image names since they can contain captial letters and special characters

---

.github/workflows/release.yml
types/info/versioninfo.go

chore: add the platform OS and ISA to the version info

---

go.mod
go.sum
transformer/external/starlarktransformer.go
transformer/kubernetes/parameterizer/parameterizer.go

feat: xml reader and query functions for starlark

---

assets/built-in/transformers/dockerfilegenerator/java/mappings/javapackageversions.yaml
transformer/dockerfilegenerator/java/gradleanalyser.go

fix: detect the java and app version for generating proper dockerfiles

---

transformer/external/starlarktransformer.go

feat: add resources dir starlark custom variable

---

transformer/external/starlarktransformer.go

feat: add output_dir starlark custom variable

---

transformer/external/starlarktransformer.go

fix: function mismatches in starlark code and fix error messages

---

common/utils.go
environment/container/dockerengine.go
environment/container/utils.go

fix: support archiving both file path and directory path

---

cmd/plan.go
cmd/transform.go

fix: fail when none of the source or customizations folder is given

---

assets/built-in/transformers/dockerfile/dockerimagebuildscript/templates/buildandpushimages_multiarch.bat
assets/built-in/transformers/dockerfile/dockerimagebuildscript/templates/buildandpushimages_multiarch.sh
assets/built-in/transformers/dockerfile/dockerimagebuildscript/templates/buildimages.bat
assets/built-in/transformers/dockerfile/dockerimagebuildscript/templates/buildimages.sh
transformer/containerimage/containerimagespushscripttransformer.go
transformer/dockerfile/dockerfilebuildscripttransformer.go

feat: allow changing where the scripts folder gets generated

---

transformer/transformer.go

chore: print better error when the transformer specified in the config is not found

---

qaengine/defaultengine.go
qaengine/httprestengine.go
types/qaengine/problem.go

fix: return a HTTP error status code when the answer is invalid

---

assets/built-in/transformers/containerimagespushscript/templates/pushimages.bat
assets/built-in/transformers/containerimagespushscript/templates/pushimages.sh
assets/built-in/transformers/dockerfile/dockerimagebuildscript/templates/buildandpushimages_multiarch.sh
assets/built-in/transformers/dockerfile/dockerimagebuildscript/templates/buildimages.bat
assets/built-in/transformers/dockerfile/dockerimagebuildscript/templates/buildimages.sh
common/constants.go
transformer/containerimage/containerimagespushscripttransformer.go
transformer/dockerfile/dockerfilebuildscripttransformer.go
types/qaengine/commonqa/commonqa.go

feat: Remove container runtime question. Allow overriding container runtime while running build or push scripts through env variable.

---

environment/environment.go
environment/types.go
transformer/cnbcontainerizer.go
transformer/external/executabletransformer.go
transformer/kubernetes/parameterizer/parameterizer.go
transformer/transformer.go
types/environment/exec.go

feat: File input/output interface for containerized transformers

---

common/pathconverters/pathconverters.go
common/utils.go
qaengine/storeengine.go

fix: config could contain invalid values not present in the options of select and multi-select questions

---

assets/built-in/transformers/containerimagespushscript/templates/pushimages.bat
assets/built-in/transformers/containerimagespushscript/templates/pushimages.sh
assets/built-in/transformers/dockerfile/dockerimagebuildscript/templates/buildandpushimages_multiarch.bat
assets/built-in/transformers/dockerfile/dockerimagebuildscript/templates/buildandpushimages_multiarch.sh
assets/built-in/transformers/dockerfile/dockerimagebuildscript/templates/buildimages.bat
assets/built-in/transformers/dockerfile/dockerimagebuildscript/templates/buildimages.sh

feat: Add instruction with examples on how to invoke the build and push images scripts

---

transformer/external/executabletransformer.go
transformer/kubernetes/parameterizer/parameterizer.go
types/transformer/input.go

feat: Added tranformer input type

---

assets/built-in/transformers/dockerfilegenerator/nodejs/templates/Dockerfile

Co-authored-by: Harikrishnan Balagopal <harikrishmenon@gmail.com>

fix: Resolve permission denied issue on OpenShift cluster for NodeJS

---

transformer/external/starlarktransformer.go

chore: remove obsolte base_directory_detect from the starlark transformer

---

transformer/dockerfilegenerator/windows/webappdockerfilegenerator.go

fix: detect the highest dot net framework version among child projects to use in the build stage

---

assets/built-in/transformers/dockerfile/dockerimagebuildscript/templates/buildimages.bat

fix: partially fixes the issue with the windows build images script

---

assets/built-in/transformers/kubernetes/operatorsfromtca/Dockerfile
assets/built-in/transformers/kubernetes/operatorsfromtca/cfservices.yaml
assets/built-in/transformers/kubernetes/operatorsfromtca/detect.py
assets/built-in/transformers/kubernetes/operatorsfromtca/preprocess.py
assets/built-in/transformers/kubernetes/operatorsfromtca/transform.py
assets/filepermissions.yaml

Also change the python code to use the new input and output format.

fix: look for external services in CfApps file instead of the CfServices file

---

transformer/compose/composeanalyser.go
transformer/external/starlarktransformer.go
transformer/kubernetes/apiresource/apiresource.go
transformer/kubernetes/apiresource/storage.go
transformer/kubernetes/apiresource/utils.go
transformer/kubernetes/kubernetestransformer.go
transformer/transformer.go

chore: some minor fixes to handle errors properly in the starlark transformer

---

common/utils.go
transformer/kubernetes/apiresource/storage.go

fix: K8s resource limits set in Starlark transformers were not being unmarshalled correctly

---

graph/server.go
qaengine/httprestengine.go

fix: QA handlers would block the POST request indefinitely in some cases, near the end of transform

---

qaengine/httprestengine.go

fix: posting a solution to the qa server was blocking till the channel cleared

---

lib/planner.go
lib/utils.go
transformer/transformer.go
transformer/utils.go
types/transformer/transformer.go

chore: better error messages and minor bug fixes

---

transformer/dockerfilegenerator/java/gradleanalyser.go
transformer/dockerfilegenerator/java/mavenanalyser.go
transformer/kubernetes/parameterizer/parameterizer.go
types/source/maven/pom.go

fix: crashes when pom file build section is absent

---

qaengine/defaultengine.go
qaengine/engine.go
qaengine/httprestengine.go
qaengine/storeengine.go
types/qaengine/commonqa/commonqa.go
types/qaengine/problem.go

fix: bug where registry url was being asked multiple times when selecting "Other" as the option

---

common/utils.go
transformer/kubernetes/k8sschema/utils.go
transformer/kubernetes/parameterizer/parameterizer.go
transformer/kubernetes/parameterizertransformer.go

feat: Loosened the paramaterization detect check

---

transformer/dockerfilegenerator/java/mavenanalyser.go

chore: fix typo

---

transformer/compose/utils.go
transformer/compose/v1v2.go
transformer/compose/v3.go
transformer/kubernetes/parameterizer/parameterizer.go

fix: Adds .env file detection in compose

---

assets/built-in/transformers/compose/composeanalyser/transformer.yaml
transformer/compose/composeanalyser.go
transformer/compose/v1v2.go
transformer/compose/v3.go
transformer/kubernetes/parameterizer/parameterizer.go

fix: Network policy is switched off in docker-compose parsing

---

transformer/compose/utils.go
transformer/compose/v1v2.go
transformer/compose/v3.go
transformer/kubernetes/parameterizer/parameterizer.go

fix: .env parsing added

---

transformer/compose/v3.go
transformer/kubernetes/parameterizer/parameterizer.go

fix: Normalized the secret and configmap names in v3 compose

---

transformer/external/starlarktransformer.go
transformer/kubernetes/apiresource/storage.go
transformer/kubernetes/parameterizer/parameterizer.go

feat: Added read binary in starlark transformer

---

environment/container/dockerengine_test.go
environment/container/testdata/buildimage/dockerfile
environment/container/testdata/dirstocopy/dir1/test1.txt
environment/container/testdata/dirstocopy/dir2/test2.txt

This PR consists of unit tests for dockerengine.go file in the container package. 
Below are the tests and their test execution status:

test: unit tests for dockerengine.go file in container package

---

filesystem/test_data/copyfile/test.txt
filesystem/utils_test.go

This PR consists of unit tests for utils.go file in the filesystem package.

test: unit test for utils.go file in filesystem package

---

cmd/graph.go
graph/layout.go

feat: make the graph more deterministic by sorting the vertices

---

lib/utils_test.go

This PR consists of unit tests for utils.go file in lib package.

test: unit tests for utils.go file in lib package

---

graph/layout.go
types/graph/graph.go

fix: the graph to show mandatory passthrough transformers on a new line

---

lib/transformer.go
transformer/external/executabletransformer.go

Signed-off-by: Mehant Kammakomati <mehant.kammakomati2@ibm.com>

fix: remove external transformer temp directories on interrupt

---

common/constants.go
transformer/compose/utils.go
transformer/compose/v1v2.go
transformer/compose/v3.go

feat: Configmap creation for compose

---

common/vcs/git_test.go

Signed-off-by: Mehant Kammakomati <mehant.kammakomati2@ibm.com>

test: test isGitBranch function

---

assets/built-in/transformers/kubernetes/operatorsfromtca/detect.py

Fixing error in https://github.com/konveyor/move2kube/issues/1079

fix: key error from detect for operatorsfromtca transformer

---

lib/utils.go

a common problem that came up for me while debugging custom transformers was adding the Starlark files to my customization directory, but forgetting the manifest for it. This silently failed to load my custom transformers, leaving me scratching my head for hours. 
This PR adds a helpful warning message if that ever happens to anyone else:

feat: warn user if custom directory contains no transformer manifests

---

Makefile
cmd/plan.go
cmd/transform.go
m2k-web-ui/package.json
m2k-web-ui/pnpm-lock.yaml
m2k-web-ui/src/index.js
m2k-web-ui/webpack.config.js

feat: add styles

---

Makefile
README.md
cmd/root.go
m2k-web-ui/package.json
m2k-web-ui/pnpm-lock.yaml
m2k-web-ui/src/index.html
m2k-web-ui/src/index.js
m2k-web-ui/src/worker.js
m2k-web-ui/webpack.config.dev.js
m2k-web-ui/webpack.config.prod.js

feat: better styles
feat: force text formatter in logrus to get color terminal output

feat: move the wasm Move2Kube transform to a web worker so that the UI remains interactive and log messages are displayed

---

m2k-web-ui/src/index.html
m2k-web-ui/src/index.js
m2k-web-ui/src/worker.js

fix: styling of file upload buttons

feat: allow uploading a config file in m2k wasm UI

---

m2k-web-ui/package.json
m2k-web-ui/pnpm-lock.yaml
m2k-web-ui/src/index.js
m2k-web-ui/src/worker.js
wasm-time-results.md

refactor: update dependencies, logger and simplify exitCode logic

test: add instrumentation to collect performance metrics

---

assets/built-in/qa/qamappings.yaml

https://github.com/konveyor/move2kube/issues/1155

fix: Update the QA categorization mappings file

---

cmd/transform.go

Sometimes the program finishes before a profile gets written.

fix: write out a heap memory profile immediately
