konveyor/move2kube

internal/common/utils.go, internal/common/utils_test.go, internal/metadata/k8sfiles.go, internal/metadata/k8sfiles_test.go
K8sFilesLoader now handles bad directory permissions error and returns it.
GetFilesByExt, GetFilesByName are fixed and return bad file permissions error when it occurs on root search directory.
This makes possible to uncomment respective tests and remove TODOs: 
https://github.com/konveyor/move2kube/blob/c9b5d0f8497ccf1dc61dd90879da9ad8b427967a/internal/common/utils_test.go#L75-L85
https://github.com/konveyor/move2kube/blob/c9b5d0f8497ccf1dc61dd90879da9ad8b427967a/internal/common/utils_test.go#L130-L140
In addition to that changes K8sFilesLoader to be more idiomatic: removes unnecessary `else` block after `continue` in `for` loop
Removes TODO for bad permission test introduced in https://github.com/konveyor/move2kube/pull/30
Closes #31
=> K8sFilesLoader: return error on bad directory permissions

scripts/install.sh, scripts/installdeps.sh
Not calling the install dependencies script from the install script to avoid complications.
The install dependencies script needs more work to improve code quality.
Note: When issue https://github.com/konveyor/move2kube/issues/34 is fixed this will need to be updated.
=> Added a install script and removed use of deprecated backticks in install_deps.sh

Makefile, scripts/builddist.go
This fixes issue https://github.com/konveyor/move2kube/issues/34
Now the folder name inside all the archives is the binary name `move2kube`
Makefiles are not easily debuggable or testable:
https://www.oreilly.com/library/view/managing-projects-with/0596006101/ch12.html
They are also very inflexible compared to proper programming languages.
The build script serves as a starting point. If the build pipelines gets more complicated the logic can be easily
added to the script instead of the Makefile.
=> Replaced complicated find command with go script. Also fixes the issue with release folder name.

.travis.yml, Makefile
make test, build, test-style are all called when running `make ci`
=> move CI routine to a make target

internal/optimizer/imagepullpolicyoptimizer_test.go, internal/optimizer/normalizecharactersoptimizer_test.go, internal/optimizer/portmergeoptimizer_test.go
- Remove assigning input to the expected output with `:=` in tests
- Replace duplicate code / Reuse functions
- Rename function
=> Refactor tests

scripts/installdeps.sh
The `~/bin` directory exists already on some systems so we shouldn't remove it even if the script fails.
=> don't remove the ~/bin directory if the script fails

internal/source/cfmanifest2kube.go
We try to parse every yaml file we find as a cfmanifest file. Naturally there will be a lot of errors during parsing since
most(if not all) yamls will not be cfmanifests.
These errors were being displayed to the user:
```
$ move2kube plan -s ref-impl
INFO[0000] Planning Translation                         
INFO[0000] [*source.DockerfileTranslator] Planning translation 
INFO[0001] [*source.DockerfileTranslator] Done          
INFO[0001] [*source.ComposeTranslator] Planning translation 
INFO[0001] [*source.ComposeTranslator] Done             
INFO[0001] [*source.CfManifestTranslator] Planning translation 
ERRO[0001] Interpolation Error Expected to find exactly one matching array item for path '/variables/name=' but found 0 
INFO[0001] [*source.CfManifestTranslator] Done          
INFO[0001] …
```
=> fix bug where errors that occurred while detecting a yaml file as a cfmanifest was displayed to the user.

cmd/move2kube/collect.go, cmd/move2kube/move2kube.go, cmd/move2kube/plan.go, cmd/move2kube/translate.go, cmd/move2kube/version.go, internal/collector/clustercollector.go, internal/collector/collector.go, internal/move2kube/collector.go, types/collection/cluster.go
`client-go` isn't properly importing openid connect.
This causes the call to get an API client to always fail.
Added a blank import as suggested in the github issue:
https://github.com/kubernetes/client-go/issues/345
Also refactored CLI by removing globals.
=> fix bug where collect was not using the API

internal/move2kube/planner.go, internal/move2kube/planner_test.go, internal/move2kube/testdata/setrootdir/nodejsplan.yaml, internal/move2kube/testdata/writeplan/nodejsplan.yaml
SetRootDir was not updating the paths because
it was checking if the path was absolute and if so
returning the same path unchanged.
Fix: rewrote the logic for SetRootDir
Also added some tests for SetRootDir, ReadPlan and WritePlan
=> fixed bug with SetRootDir and added tests

docs/tutorials/docker-compose.md
Rename "Migrating Docker apps to Kubernetes" to "Migrating Docker compose/swarm apps to Kubernetes" - https://github.com/konveyor/move2kube/issues/249
=> Rename docker-compose tutorial

internal/apiresource/imagestream.go
The bug is in ImageStream. The dockerImageRepository field
was deprecated in favor of .spec.tags.[].from.name
We are using both fields. Openshift ignores the deprecated
field and only uses the new field .spec.tags.[].from.name
To make matters worse, we only specify the short image name in
the new field. Example:
```
dockerImageRepository: docker.io/username/golang
tags:
- name: latest
from:
kind: DockerImage
name: golang
```
results in it pulling docker.io/library/golang:latest
Fix: Avoid using the deprecated field and provide the
fully qualifed image name and tag in the new field.
=> fixes bug where some apps where going into CrashLoopBackoff when used with DeploymentConfig on Openshift

_includes/head_custom.html, _layouts/default.html, _sass/custom/custom.scss
https://github.com/konveyor/move2kube/issues/225
The `Back to top` link was overlapping with the Konveyor logo on the the mobile version of the website.
=> Resolve Back to top link issue on mobile website

.grenrc.js, internal/move2kube/planner.go, internal/qaengine/engine.go
This is useful if we are translating a docker compose
project for example. We know for sure that we only
want services detected by Compose2Kube.
=> feat: ask which translation types the user is interested in

.github/workflows/publish.yml, .github/workflows/release.yml
For major releases we might want to have the changes from all
the pre-releases also included in the release notes.
We also might want to use a different commit to do the release.
=> ci: added support for specifying commit and previous tag while releasing

internal/source/cfmanifest2kube.go
=> fix: If cf app path directory is missing, assume manifest path as app source location

.github/workflows/releaseinfo.yml, .gitignore
This info will be displayed on the website.
This info will also be used by the release
UI to decide the tag, commit, etc. to use
for new releases.
Also ignore node_modules in main branch to
allow easy switching to and from gh-pages.
=> feat: write release information to a file

.github/workflows/release.yml, .grenrc.js
Also use the draft title as a mutex.
The title will have the prefix [WIP]
while the workflow is in progress.
The UI will detect this and not allow
publishing the draft.
=> ci: create branch if necessary in the release workflow

.github/workflows/release.yml
See https://github.com/github/hub/issues/1817
Editing a release draft using the API causes
the draft to become untagged.
Also add logic to delete the tag and recreate
it if it already exists.
=> ci: workaround for a bug in the github API

.gitignore
=> fix: .brew_home is created during brew bottling causing git tree state to become dirty

cmd/common/utils.go, cmd/kubectltranslate/kubectltranslate.go, cmd/move2kube/translate.go
also add the check to kubectl-translate plugin
=> fix: arguments to IsParent were switched

internal/apiresource/apiresource.go, internal/common/utils.go
=> fix: When merging two runtime.Objects, bring them to same version before merging

.github/workflows/build.yml, .github/workflows/prbuild.yml, .github/workflows/release.yml
Issue seems to be with v3.94 of upx that comes installed by
default in ubuntu-latest images of Github actions.
A number of very similar issues:
https://github.com/upx/upx/issues/450
https://github.com/upx/upx/issues/222
=> chore: fix an issue with upx and mac where the process gets killed immediately

Gemfile, Gemfile.lock, _config.yml, _includes/head.html, _layouts/default.html
GitHub builds the website using the --safe option as mentioned here:
https://jekyllrb.com/docs/plugins/installation/
So only some plugins are allowed. The complete list of whitelisted
plugins is given here: https://pages.github.com/versions/
The google tag manager plugin https://github.com/t-richards/jekyll-google-tag-manager
is not listed there.
Fix is to remove the plugin and add the tag manually.
=> chore: github only allows some whitelisted plugins, so remove the plugin and add gtm tag manually

Makefile, internal/common/generator/generator.go, internal/common/generator/generator_test.go, scripts/builddist.go, scripts/detectgoversion/detect.go
=> fix: match the golang version in go.mod

index.yaml
https://github.com/konveyor/move2kube/pull/513
=> fix: index.yaml had the wrong semver due to a recent bug (now fixed) in the release UI

_config.yml
See https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/adding-a-theme-to-your-github-pages-site-using-jekyll#adding-a-theme
=> fix: github only supports a small list of themes

Gemfile, Gemfile.lock, _config.yml
=> fix: remove just-the-docs theme from gemfile and let the jekyll-remote-theme plugin take care of it

api/planner.go
=> fix: Prevent crash when all transformers for a service become unselected

assets/inbuilt/transformers/executable/dockerfile/golang/golang.yaml, filesystem/merger.go, internal/transformer/processors.go
feat: Process all source mappings before other mapping types to prevent overwrite
=> feat: Process all source mappings before other mapping types to prevent overwrite

internal/transformer/classes/analysers/dockerfileparser.go
Example: 
- `FROM mcr.microsoft.com/dotnet/sdk:5.0 AS buildImg` -Select linux container
-  `FROM --platform=windows/amd4 mcr.microsoft.com/dotnet/sdk:5.0 AS buildImg`- Select windows container
=> fix: Target windows node if the dockerfile template is windows platform based

README.md
=> chore: update readme with new instructions for UI

transformer/processors.go
This PR adds the returned errors to the log message. It should help to clarify the somewhat ambiguous/identical log messages. It appears that there are multiple reasons for an error to occur. For example, the `process` function which gets called when doing a `TemplateCopy` could error in multiple ways while processing a file, symlink or directory. The uniqueness of the possible errors can be valuable in situations where we'd need to debug using these log messages.
=> refactor: added the error to the log messages when processing path mappings

collector/clustercollector.go
=> fix: Remove space from cluster name in move2kube collect

assets/inbuilt/transformers/dockerfilegenerator/java/earrouter/earrouter.yaml, assets/inbuilt/transformers/dockerfilegenerator/java/warrouter/warrouter.yaml
When "intercepts" was changed to "passthrough" concept,
some of the built-in transformer yamls were not updated properly with the new field.
The WAR router transformer was running in parallel with the
WAR processor transformers (JBoss, Liberty, Tomcat).
This causes extra questions to be asked and ports 8080 and 9080 to come up together.
=> fix: bug where 2 questions about port are asked

common/utils.go, transformer/dockerfilegenerator/pythondockerfiletransformer.go
```
$ move2kube plan -s train-ticket/
INFO[0000] Configuration loading done                   
INFO[0000] Planning Transformation - Base Directory     
INFO[0000] [CloudFoundry] Planning transformation       
INFO[0000] [CloudFoundry] Done                          
INFO[0000] [ComposeAnalyser] Planning transformation    
INFO[0000] Identified 69 named services and 0 to-be-named services 
INFO[0000] [ComposeAnalyser] Done                       
INFO[0000] [DockerfileDetector] Planning transformation 
INFO[0002] Identified 1 named services and 42 to-be-named services 
INFO[0002] [DockerfileDetector] Done                    
INFO[0002] [Base Directory] Identified 70 named services and 42 to-be-named services 
INFO[0002] Transformation planning - Base Directory done 
INFO[0002] Planning …
```
=> fix: panic during QA when transforming some apps like train-ticket

transformer/compose/v3.go, transformer/kubernetes/apiresource/storage.go, transformer/kubernetes/k8sschema/utils.go, transformer/kubernetes/parameterizertransformer.go, transformer/transformer.go
In docker compose YAML file it is not necessary to have a volume name
https://docs.docker.com/compose/compose-file/compose-file-v3/#short-syntax-3
=> fix: empty metadata.name or service name when transforming docker compose with volume

transformer/compose/v3.go
=> fix: fix docker compose v2 parsing warning from v3 parser

go.mod, go.sum
Contributed a fix to go-cfclient- https://github.com/cloudfoundry-community/go-cfclient/pull/305.
When not logged in to CF, `move2kube collect -a cf` was returning a panic.
```
$ move2kube collect -a cf
INFO[0000] Begin collection                             
INFO[0000] [*collector.CfAppsCollector] Begin collection 
panic: runtime error: slice bounds out of range [7:0]
goroutine 1 [running]:
github.com/cloudfoundry-community/go-cfclient.loadCFHomeConfig({0xc00005604d?, 0x7?})
/Users/akash/go/pkg/mod/github.com/cloudfoundry-community/go-cfclient@v0.0.0-20220111154238-f50d0fa052b3/client.go:122 +0x17b
github.com/cloudfoundry-community/go-cfclient.NewConfigFromCFHome({0x0?, 0x0?})
/Users/akash/go/pkg/mod/github.com/cloudfoundry-community/go-cfclient@v0.0.0-20220111154238-f50d0fa052b3/client.g …
```
=> fix: Resolve panic error during move2kube cf collect when not logged in to cf

transformer/transformer.go
We are trying to extend Move2Kube and want to create some specific transformers in Golang. But the code currently doesn't allow that. This PR adds a `RegisterTransformer` method that can used to add transformers from outside the module and helps us achieve our goal.
We also did consider the Starlark approach, but found this to limited.
=> feat: Registering transformers after init()

collector/cfappscollector.go, collector/cfservicescollector.go, collector/cfutils.go
With `ibmcloud login`
```console
➜  move2kube git:(ibmcloud-cf-collect) move2kube collect -a cf        
INFO[0000] Begin collection                             
INFO[0000] [*collector.CfAppsCollector] Begin collection 
INFO[0015] Changing metadata name from IBM Cloud to ibm-cloud 
INFO[0019] [*collector.CfAppsCollector] Done            
INFO[0019] [*collector.CfServicesCollector] Begin collection 
INFO[0039] Changing metadata name from IBM Cloud to ibm-cloud 
INFO[0039] [*collector.CfServicesCollector] Done        
INFO[0039] Collection done                              
INFO[0039] Collect Output in [/Users/akash/github/move2kube/m2k_collect]. Copy this directory into the source directory to be used for planning.
```
When login is through `ibmcloud login` and not `cf login` with debug …
=> feat: Add support for ibmcloud cf cli to move2kube collect

assets/built-in/transformers/dockerfilegenerator/nodejs/transformer.yaml, transformer/dockerfilegenerator/nodejsdockerfiletransformer.go
This PR puts a temporary fix for the missing Node.js version in the generated Dockerfile which happens in case of conditional node version (say, <16.15) in the package.json file.
=> fix: Temporary fix for the missing Node.js version in the generated Dockerfile due to package.json file

environment/container/container.go, environment/container/dockerengine.go, environment/container/dockerengine_test.go
New output after the fix
```
$ move2kube plan -s src/ --preset enablecontainerizedtransformers
INFO[0000] Pulling container image quay.io/konveyor/hello-world. This could take a few mins. 
FATA[0000] failed to initialize the container engine. Error: "failed to use docker as the container engine. Error: \"unable to run test image 'quay.io/konveyor/hello-world' as a container. Error: \\\"failed to pull the image 'quay.io/konveyor/hello-world'. Error: \\\\\\\"failed to pull the image 'quay.io/konveyor/hello-world' using the docker client. Error: \\\\\\\\\\\\\\\"Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?\\\\\\\\\\\\\\\"\\\\\\\"\\\"\""
```
We exit with error since no container engine is found.
Signed-off-by: Harikrishnan Balagopal …
=> fix: panic when docker is not installed and CNB containerizer is used

transformer/dockerfilegenerator/nodejsdockerfiletransformer.go
=> fix: warn only if the .env file was found and parsing failed

common/utils.go, lib/transformer.go
The old behaviour simply selects the first valid transformation option without
informing the user. It also used to ignore any service which doesn't have valid
transformation options with just a debug message.
New behaviour:
```
? Select all services that are needed:
ID: move2kube.services.[].enable
Hints:
- The services unselected here will be ignored.
eShop
INFO[0000] Found multiple transformation options for the service 'eShop'. Selecting the first valid option. 
INFO[0000] Using the transformation option 'WinConsoleApp-Dockerfile' for the service 'eShop'.
```
=> fix: inform the user when there are multiple transformation options for a service

transformer/cloudfoundrytransformer.go, transformer/cnbcontainerizer.go, transformer/dockerfilegenerator/dotnetcoredockerfilegenerator.go, transformer/dockerfilegenerator/golangdockerfiletransformer.go, transformer/dockerfilegenerator/java/earanalyser.go, transformer/dockerfilegenerator/java/gradleanalyser.go, transformer/dockerfilegenerator/java/jaranalyser.go, transformer/dockerfilegenerator/java/mavenanalyser.go, transformer/dockerfilegenerator/java/waranalyser.go, transformer/dockerfilegenerator/java/zuulanalyser.go, transformer/dockerfilegenerator/nodejsdockerfiletransformer.go, transformer/dockerfilegenerator/phpdockerfiletransformer.go, transformer/dockerfilegenerator/pythondockerfiletransformer.go, transformer/dockerfilegenerator/rubydockerfiletransformer.go, transformer/dockerfilegenerator/rustdockerfiletransformer.go, transformer/dockerfilegenerator/windows/consoleappdockerfilegenerator.go, transformer/dockerfilegenerator/windows/silverlightwebappdockerfilegenerator.go, transformer/dockerfilegenerator/windows/webappdockerfilegenerator.go, types/qaengine/config.go, types/transformer/artifacts/artifacts.go, types/transformer/artifacts/dotnet.go
Also normalize the app name and child project names to avoid inconsistencies
in the names given to the same service by different transformers.
=> fix: difference between how multi-select questions were read and written to config was causing unnecessary questions to be asked

go.mod, go.sum
I can not build with docker/distribution 2.8.0. It looks like there was a problem that was corrected in 2.8.1
https://github.com/distribution/distribution/issues/3590
`verifying github.com/docker/distribution@v2.8.0+incompatible: checksum mismatch`
=> fix: Update docker/distrbution dep to 2.8.1

Makefile
=> feat: Generate binaries for s390x/Power platforms

common/constants.go, common/cryptoutils.go, common/utils.go, environment/container/dockerengine.go, environment/container/utils.go, filesystem/templatecopy.go
=> feat: add archive utils with compression options

transformer/external/starlarktransformer.go
=> feat: add starlark custom functions for crypto and archive utils

transformer/external/starlarktransformer.go
=> fix: use snake case for starlark custom functions

cmd/plan.go, common/constants.go
=> feat: let the user decide if they want planning to fail if no services are detected

go.mod, go.sum, transformer/transformer.go
=> chore: update the go.mod file to fix minor issues

.github/workflows/build.yml, .github/workflows/prbuild.yml, .github/workflows/release.yml, Makefile, assets/built-in/transformers/dockerfilegenerator/windows/winconsole/transformer.yaml, assets/built-in/transformers/dockerfilegenerator/windows/winsilverlightweb/transformer.yaml, cmd/plan.go, cmd/transform.go, lib/planner.go, lib/transformer.go, transformer/transformer.go, types/plan/plan.go
See https://github.com/konveyor/move2kube/pull/888
=> fix: deselect the console and silverlight transformer by default to avoid conflicts with dotnet webapp transformer

cmd/collect.go, environment/container/dockerengine_test.go
=> chore: errors were not beind displayed properly in a few places

transformer/dockerfilegenerator/pythondockerfiletransformer.go, transformer/dockerfilegenerator/rustdockerfiletransformer.go, transformer/kubernetes/k8sschema/utils.go
chore: `io/ioutil` package was deprecated, functionality split into the `os` and `io` packages
See https://github.com/go-critic/go-critic/issues/1019
=> fix: the rust transformer was not detecting the rust service in language-platforms

transformer/dockerfilegenerator/dotnetcoredockerfilegenerator.go, transformer/dockerfilegenerator/windows/consoleappdockerfilegenerator.go, transformer/dockerfilegenerator/windows/silverlightwebappdockerfilegenerator.go, transformer/dockerfilegenerator/windows/webappdockerfilegenerator.go, types/source/dotnet/csproj.go
Also add support for Dot Net Framework version 3.5
=> fix: bug where the .dll filename was normalized when it shouldn't be in the Dockerfiles generated for Dot Net Core

common/utils.go, qaengine/engine.go, transformer/kubernetes/apiresource/storage.go
=> fix: IR config was not getting properly unmarshalled leading to empty containers in the deployment yamls

scripts/install.sh
I have tested the Move2Kube installation on the ppc64le Power VM after making the changes to the `install.sh` script locally.
```console
[root@test-lab-vm ~]# MOVE2KUBE_TAG='v0.4.0-alpha.0' bash <install.sh
Installing move2kube
Downloading https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64
Downloading https://github.com/konveyor/move2kube/releases/download/v0.4.0-alpha.0/move2kube-v0.4.0-alpha.0-linux-ppc64le.tar.gz
Downloading https://github.com/konveyor/move2kube/releases/download/v0.4.0-alpha.0/move2kube-v0.4.0-alpha.0-linux-ppc64le.tar.gz.sha256sum
Verifying checksum
Preparing to install move2kube into the directory: /usr/local/bin
If it fails, you can retry with a different installation directory. Example: MOVE2KUBE_INSTALL_DIR=/my/new/install/dir
Successfully …
```
=> feat: Support installing Move2Kube using the installation script on Power, s390x and arm64 systems

assets/built-in/transformers/kubernetes/parameterizer/parameterizers/replicas.yaml, transformer/kubernetes/parameterizer/parameterizer.go, transformer/kubernetes/parameterizer/types.go, transformer/kubernetes/parameterizer/utils.go, transformer/kubernetes/parameterizertransformer.go
1. Run `move2kube plan -s src` and `move2kube transform`
2. Specify a different number of replicas
```
? Provide the minimum number of replicas each service should have
ID: move2kube.minreplicas
Hints:
- If the value is 0 pods won't be started by default
33
```
The output yamls and helm chart values.yaml should have the replicas set to `33`
In the output `deploy/yamls/` all the `Deployment` yamls have the replicas set to `33`.
In the output `deploy/yamls-parameterized/` folder has Helm chart, Kustomize and Openshift Template all of which have replicas set to `2`.
This is because the `default` value in a parameterizer yaml always replaces the original value at the location.
https://github.com/konveyor/move2kube/blob/main/assets/built-in/transformers/kubernetes/parameterizer/parameterizers/r …
=> fix: when the user specifies a replicas other than 2 it is not properly reflected in the Helm chart values.yaml

transformer/dockerfilegenerator/windows/webappdockerfilegenerator.go
=> fix: use forward slashes for paths in Dockerfiles because backward slash is a special character

assets/built-in/transformers/dockerfilegenerator/nodejs/templates/Dockerfile
```console
building image frontend
[+] Building 5.1s (9/10)                                                                           
=> [internal] load build definition from Dockerfile                                          0.1s
=> => transferring dockerfile: 868B                                                          0.0s
=> [internal] load .dockerignore                                                             0.0s
=> => transferring context: 56B                                                              0.0s
=> [internal] load metadata for registry.access.redhat.com/ubi8/nodejs-14:latest             0.0s
=> [internal] load build context                                                             0.2s
=> => transferring context: 2.91MB …
```
=> fix: Prevent docker build from failing if .npm folder is missing

transformer/kubernetes/irpreprocessor/registrypreprocessor.go
Fixes https://github.com/konveyor/move2kube/issues/928
The generated deployment yaml when selected `no authentication`.
```console
apiVersion: apps/v1
kind: Deployment
metadata:
creationTimestamp: null
labels:
move2kube.konveyor.io/service: nodejs
name: nodejs
spec:
progressDeadlineSeconds: 600
replicas: 2
revisionHistoryLimit: 10
selector:
matchLabels:
move2kube.konveyor.io/service: nodejs
strategy:
rollingUpdate:
maxSurge: 25%
maxUnavailable: 25%
type: RollingUpdate
template:
metadata:
creationTimestamp: null
labels:
move2kube.konveyor.io/service: nodejs
name: nodejs
spec:
containers:
- image: quay.io/latest4/nodejs:latest
imagePullPolicy: Always
name: nodejs
ports:
- containerPort: 8080
protocol: TCP
resources: {}
terminationMessagePath: /dev/termination-log
terminationMessagePolicy: …
```
=> fix: Do not add the image pull secret to the service IR if selected no authentication

cmd/utils.go
=> chore: update the message shown when the output directory exists

transformer/dockerfilegenerator/java/zuulanalyser.go
There was a panic error if the zuul path is `/` and not `/**`.
```yaml
zuul:
routes:
api: /api/**
web: /
```
```console
$ move2kube plan -s docker-compose-services
panic: runtime error: slice bounds out of range [:-1]
goroutine 1 [running]:
github.com/konveyor/move2kube/transformer/dockerfilegenerator/java.(*ZuulAnalyser).Init(0xc0008aeb00, {{{0xc0010edb20, 0x1e}, {0xc0010d2ef0, 0xb}}, {{0xc0010d2f24, 0xc}, 0xc0010ee810}, {{0xc0009f3040, 0x92}, ...}}, ...)
/Users/akash/github/move2kube/transformer/dockerfilegenerator/java/zuulanalyser.go:65 +0x409
github.com/konveyor/move2kube/transformer.InitTransformers(0xc000f98fb8?, {0x3c3b9b8, 0xc00048c150}, {0xc00015a0a0, 0x41}, {0x0, 0x0}, {0x3634ba9, 0x9}, 0x0, ...)
```
This PR fixes the above panic error.
```console
$ move2kube plan -s …
```
=> fix: Resolve panic error in Zuul analyser for path not ending with double asterisk

assets/built-in/transformers/dockerfilegenerator/golang/mappings/golangversions.yaml, assets/built-in/transformers/dockerfilegenerator/golang/templates/Dockerfile, assets/built-in/transformers/dockerfilegenerator/golang/transformer.yaml, assets/filepermissions.yaml, transformer/dockerfilegenerator/golangdockerfiletransformer.go
Changed the base image to [registry.access.redhat.com/ubi8/go-toolset](https://catalog.redhat.com/software/containers/ubi8/go-toolset/5ce8713aac3db925c03774d1) for building the app with multi-arch support. The base image supports amd64/arm64/ppc64le/s390x.
I was successfully able to build the multi-arch image for amd64, arm64 and ppc64le (Power), but for s390x (Z) arch the build gets stuck at `RUN go build -o ./bin/golang`.
```console
➜  scripts git:(main) ✗ ./buildandpushimages_multiarch.sh quay.io akashnayak linux/amd64,linux/arm64,linux/ppc64le
building and pushing image golang
[+] Building 60.7s (29/29) FINISHED                                                                     
=> [internal] load .dockerignore                                                                  0.0s
=> …
```
=> feat: Update the Golang Dockerfilegenerator transformer to support multi-arch build

cmd/transform.go, qaengine/engine.go, types/qaengine/cache.go, types/qaengine/config.go, types/qaengine/qaengine.go
=> feat: obfuscate passwords by base64 encoding them before writing to config and cache

transformer/external/starlarktransformer.go, transformer/transformer.go
Example bug in a Starlark transformer:
```
if 'HostPath' in v:
path = v['HostPath']['Path']
```
and error output shows the exact line number and the starlark file name:
```
ERRO[0000] failed to transform artifacts using the transformer named 'ConfigMapGen' . Error: failed to call the starlark function '<function transform>' . The call stack is:
Traceback (most recent call last):
/var/folders/dt/y3srs7vs6pz9bqwrbjwt38pc0000gp/T/move2kube313903856/m2kassets/custom/cfg-map-generator/configmapgen.star:49:45: in transform
Error: unhandled index operation NoneType[string]
Error: unhandled index operation NoneType[string] 
```
=> feat: show the call stack and line numbers when an error occurs while running starlark functions like transform

transformer/dockerfilegenerator/dotnetcoredockerfilegenerator.go, types/source/maven/pom.go
Also fixes an error that was shown when the `.csproj` file doesn't contain a `ItemGroup` element.
=> fix: panic in dotnetcore transformer when publish profile XML files are specified

.github/workflows/build.yml, .github/workflows/release.yml
This is required as set-output would be completely removed and the workflows can potentially break starting June 2023.
Fyi - 
I am new to open source, however, I have some working knowledge on git and enterprise github.
I tried following the conventions as much as possible, please guide me if I have missed anything in this pull request.
thank you.
=> fix: set-output throws error in ci/cd starting June 2023

environment/container/dockerengine_test.go, environment/container/podmanengine.go, environment/container/podmanengine_test.go
This PR consists of unit tests for podmanengine.go file in the container package.
Below are the tests and their test execution status:
=> test: unit tests for podmanengine.go file in container package

transformer/compose/composeanalyser.go
```console
$ move2kube plan -s single-service/
INFO[0000] Configuration loading done                   
INFO[0000] Start planning                               
INFO[0000] Planning started on the base directory: '....../single-service' 
INFO[0000] [CloudFoundry] Planning                      
INFO[0000] [CloudFoundry] Done                          
INFO[0000] [ComposeAnalyser] Planning                   
INFO[0000] Identified 1 named services and 0 to-be-named services 
INFO[0000] [ComposeAnalyser] Done                       
INFO[0000] [DockerfileDetector] Planning                
INFO[0000] [DockerfileDetector] Done                    
INFO[0000] [Base Directory] Identified 1 named services and 0 to-be-named services 
INFO[0000] Planning finished on the base directory: …
```
=> fix: panic when run on docker compose single service sample because []interface{} is not []string

cmd/flags.go, cmd/transform.go, lib/transformer.go, transformer/transformer.go
```console
$ move2kube transform -s src/ -c cust/
........................
INFO[0013] Transformer 'Parameterizer' processing 4 artifacts 
INFO[0013] Transformer Parameterizer Done               
INFO[0013] Transformer 'ReadMeGenerator' processing 4 artifacts 
INFO[0013] Transformer ReadMeGenerator Done             
INFO[0013] Transformer 'ClusterSelector' processing 1 artifacts 
INFO[0013] Transformer ClusterSelector Done             
INFO[0013] Transformer 'Tekton' processing 1 artifacts  
INFO[0013] Transformer Tekton Done                      
INFO[0014] Created 31 pathMappings and 5 artifacts. Total Path Mappings : 176. Total Artifacts : 47. 
ERRO[0014] exceeded the max number of iterations: 10 . stopping. 
INFO[0014] Transformation done                          
INFO[0014] …
```
=> feat: add a flag to limit the maximum number of iterations

environment/container/dockerengine_test.go, environment/container/podmanengine_test.go
This PR consists of update in image to ubi8 and hello-world.
=> fix: update image to ubi8 and hello-world

assets/built-in/transformers/dockerfilegenerator/nodejs/templates/Dockerfile
Fixes- https://github.com/konveyor/move2kube/issues/1016
Old Dockerfile
```dockerfile
FROM registry.access.redhat.com/ubi8/nodejs-16
COPY . .
RUN npm install
USER root
RUN mkdir -p /opt/app-root/src/.npm
RUN chown -R 1001:0 /opt/app-root/src/.npm
RUN chmod -R 775 /opt/app-root/src/.npm
USER 1001
EXPOSE 8080
CMD npm run start
```
```console
✗ ./buildimages.sh
building image cfnodejsapp
[+] Building 1.2s (7/10)                                                                           
=> [internal] load build definition from Dockerfile                                          0.0s
=> => transferring dockerfile: 879B                                                          0.0s
=> [internal] load .dockerignore                                                             0.0s
=> => …
```
=> fix: Resolve docker build failure of NodeJS application

cmd/plan.go, cmd/transform.go
Corresponding docs link PR is at https://github.com/konveyor/move2kube-website/pull/117
=> docs: add git support as part of usage information

common/vcs/git.go
fixed based on https://docs.github.com/en/get-started/using-git/dealing-with-special-characters-in-branch-and-tag-names#naming-branches-and-tags
=> fix: follow git branch naming convention based on docs.github.com

environment/peercontainer.go
Signed-off-by: Mehant Kammakomati <mehant.kammakomati2@ibm.com>
=> fix: fail when path is not a directory for peercontainer upload/download

common/constants.go, common/utils.go, transformer/dockerfile/dockerfileparsertransformer.go, transformer/kubernetes/apiresource/pipeline.go, transformer/kubernetes/apiresource/triggertemplate.go, transformer/kubernetes/irpreprocessor/registrypreprocessor.go, types/ir/ir.go
Also put relative paths in the Tekton pipeline when there is no git repo. This makes the pipeline more usable.
Example:
```yaml
- name: build-push-1
params:
- name: IMAGE
value: $(params.image-registry-url)/golang
- name: DOCKERFILE
value: '<TODO: fill this prefix starting from the root of the git repo>/golang/Dockerfile'
- name: CONTEXT
value: '<TODO: fill this prefix starting from the root of the git repo>/golang'
```
=> feat: add workspaces to Tekton pipeline for git repo creds and registry creds

common/utils.go, transformer/external/starlarktransformer.go
Fixes: #1049 . Can fill a Golang template in Starlark transformers now:
```python
my_template = """
Hi {{ .Name }}!
"""
data = {
"Name": "John Doe"
}
filled_template = template.eval_template(my_template, data)
print(filled_template)
```
=> feat: add ability to fill a Golang template from a Starlark transformer

collector/imagescollector.go
Resolves https://github.com/konveyor/move2kube/issues/1052
There was no if condition to check whether the `err` is nil or not. So, `move2kube collect -a dockercompose` would always return the error message even if the `err` is nil.
=> fix: Resolve move2kube images collect error

cmd/plan.go, cmd/transform.go, common/download/download.go, common/download/httpdownload.go, common/utils.go, qaengine/engine.go
Allow giving config files as http URLs 
example usage
```
move2kube transform -s samples/python --overwrite --config http://localhost:8000/m2kconfig2.yaml --config http://localhost:8000/m2kconfig3.yaml --overwrite
```
=> feat: input config files from http links

collector/imagescollector.go
Fixes- https://github.com/konveyor/move2kube/issues/1054
```console
$ move2kube collect -a dockerswarm --log-level debug
INFO[0000] Begin collection                             
INFO[0000] [*collector.ImagesCollector] Begin collection 
DEBU[0000] images : [quay.io/konveyor/move2kube-ui:latest nginx:stable-alpine ] 
DEBU[0000] UserID not available in image metadata for [quay.io/konveyor/move2kube-ui:latest] 
DEBU[0000] UserID not available in image metadata for [nginx:stable-alpine]       
WARN[0000] Image [] not available in local image repo. Run "docker pull " 
INFO[0000] [*collector.ImagesCollector] Done            
INFO[0000] Collection done                              
INFO[0000] Collect Output in [/Users/akash/github/move2kube-demos/m2k_collect]. Copy this directory into the source …
```
=> fix: Resolve no clean images detected issue; Remove extra blank image name

README.md
I have updated the documentation link to point to the [home page ](https://move2kube.konveyor.io/). 
Fixes #1064
=> docs: Update the documentation link in Readme file

filesystem/replicator_test.go, filesystem/test_data/replicator_test/destination_same.txt, filesystem/test_data/replicator_test/source_same.txt
Added tests for replicateProcessFileCallBack in the filesystem package. These tests cover 4 cases
1. Source file does not exist, should return an error
2. Destination file doesn't exist, should copy the source file
3. Destination file exists but is different, should copy the source file
4. Destination file exists and is the same, should return nil without copying
Fixes a part of #881
=> test: add tests for replicateProcessFileCallBack

README.md
=> fix: Update Documentation badge link

filesystem/replicator_test.go
Replace  ioutil.Readfile -> os.Readfile. As it is deprecated from go v1.16.
=> fix: replace deprecated ioutil readfile function

filesystem/replicator_test.go
Added test for replicateDeletionCallback in the filesystem package. These tests cover 2 cases
1. Destination folder gets created
2. Created destination folder has the same permissions as the source.
Fixes a part of https://github.com/konveyor/move2kube/issues/881
=> test: add tests for replicateDeletionCallback

common/constants.go, transformer/kubernetes/apiresource/argocdapplication.go
I am new to open source. I made the PR referring to this link: https://github.com/konveyor/move2kube/blob/main/contributing.md Please LMK if I need to correct something. 
This PR Solves: https://github.com/konveyor/move2kube/issues/930
I've built and tried Move2kube project. I am having trouble in testing this change. Can somebody suggest. Thanks!
=> fix: take destNamespace from user

cmd/flags.go, cmd/transform.go
```
$ move2kube version -l
version: v0.3.0+unreleased
gitCommit: 3a847c3366c4d2cd70167fb98f79477d683094d8
gitTreeState: clean
goVersion: go1.21.0
platform: darwin/arm64
$ move2kube transform -s src/ --qa-skip --profile mycpuprofile.pprof
$ go tool pprof /Users/haribala/go/bin/move2kube mycpuprofile.pprof
```
=> test: add a flag to generate the CPU profile for the transform command

assets/built-in/qa/qamappings.yaml, assets/filepermissions.yaml, cmd/flags.go, cmd/transform.go, common/constants.go, go.mod, go.sum, qaengine/cliengine.go, qaengine/utils.go, transformer/external/starlarktransformer.go, types/qaengine/problem.go, types/qaengine/qamapping.go
Categorizes QA questions as defined by a new mappings file. Adds two flags: --qa-enable and --qa-disable for finer grained control
=> fix: categorize QA engine questions

common/constants.go, transformer/kubernetes/apiresource/service.go
=> feat: add support for TLS termination policies to OpenShift Routes

common/sshkeys/sshkeys.go
When using the `qa-skip` flags, the method `loadSSHKeysOfCurrentUser` was not setting a default value:
```go
selectedOption := qaengine.FetchSelectAnswer(common.ConfigRepoLoadPrivKey, message, nil, "", options, nil)
```
This is causing a fatal error:
```
\"Unable to fetch answer. Error: 
"the QA problem object is invalid: {ID:move2kube.repo.keys.load Type:Select Desc:The CI/CD pipeline needs access to the git repos in order to clone, build and push.
If any of the repos require ssh keys you will need to provide them.
Select an option: Hints:[] Options:[Load the private SSH keys from the directory '%!s(MISSING)'/root/.ssh Provide your own key No, I will add them later if necessary.] Default: Answer:<nil> Validator:<nil> Categories:[]} . Error: the default [] is not present in the options …
```
=> fix: add default value for loadSSHKeysOfCurrentUser qa problem

cmd/flags.go, cmd/plan.go, cmd/transform.go, common/vcs/git.go, common/vcs/git_test.go, common/vcs/limit.go, common/vcs/vcs.go, environment/environment.go, go.mod, lib/planner.go, lib/transformer.go, lib/utils.go, types/plan/planutils.go
Set a max repo size while cloning.
Added a `--max-clone-size` flag to both the `plan` and `transform` commands.
It is the maximum size in bytes. Default is -1 where negative values mean infinite bytes.
DOES NOT FIX the bug found in the `main` branch while making this PR https://github.com/konveyor/move2kube/issues/1110
`af4d50b1e5522c2a41c34894aa8cf433f5845bb9`
=> fix: limit the size of the git clone

filesystem/merger_test.go
i) This test case covers a scenario when function is called with a non-existent source file and an existing destination directory
fixes a part of #881
=> test: add tests for mergeDeletionCallBack

filesystem/merger_test.go
i) this test covers a scenario when the source and destination files are of same content.
fixes a part of #881
=> test: added test for mergeProcessFileCallBack function

filesystem/merger_test.go
ii) test for scenario which checks for permissions of the destination directory to match the permissions of the source file when both the source file and destination directory exist
fixes a part of #881
=> test: added test for mergeDeletionCallBack

go.mod
Fix the error
```shell
$ VERSION='v0.3.12-rc.0' make dist
rm -rf /Users/haribala/Documents/code/remote/github.com/konveyor/move2kube/bin /Users/haribala/Documents/code/remote/github.com/konveyor/move2kube/_dist
go clean -cache
cd / && GO111MODULE=on go install  github.com/mitchellh/gox@v1.0.1
go: downloading github.com/mitchellh/gox v1.0.1
go: downloading github.com/mitchellh/iochan v1.0.0
go: downloading github.com/hashicorp/go-version v1.0.0
CGO_ENABLED=0 /Users/haribala/go/bin/gox -parallel=3 -output="/Users/haribala/Documents/code/remote/github.com/konveyor/move2kube/_dist/{{.OS}}-{{.Arch}}/move2kube" -osarch='darwin/amd64 darwin/arm64 linux/amd64 linux/arm64 linux/s390x linux/ppc64le windows/amd64' -ldflags '-w -s -X github.com/konveyor/move2kube/types/info.version=v0.3.12-rc.0 -X …
```
=> fix: gox cross compilation was failing asking for a `go mod tidy`

Dockerfile
When I try to use ssh key to clone the git repo:
```
move2kube plan -s git+ssh://bitbucket.org/gfarache31/m2k-test@master
```
I get the following error:
```
FATA[0000] failed to create the plan. Error: "failed to clone the repo 'git+ssh://bitbucket.org/gfarache31/m2k-test'. Error: failed to clone using vcs url 'git+ssh://bitbucket.org/gfarache31/m2k-test' and clone options {CommitDepth:1 Overwrite:true MaxSize:-1 CloneDestinationPath:/tmp/move2kube1491402545/m2ksources}. Error: failed to perform clone operation using git with options {URL:git@bitbucket.org:gfarache31/m2k-test Auth:<nil> RemoteName:origin ReferenceName:refs/heads/main SingleBranch:true Mirror:false NoCheckout:false Depth:1 RecurseSubmodules:0 Progress:<nil> Tags:2 InsecureSkipTLS:false CABundle:[] ProxyOptions:{URL: …
```
=> fix: install openssh in Dockerfile in order to be able to clone repo using ssh keys

assets/built-in/qa/qamappings.yaml, cmd/flags.go, cmd/transform.go, cmd/utils.go, lib/planner.go, lib/utils.go, types/qaengine/qamapping.go
Moved ports questions to a separate category
Co-authored-by: Harikrishnan Balagopal <harikrishnan.balagopal@ibm.com>
=> feat: Allow overriding the default QA Mappings file

qaengine/cliengine.go, qaengine/engine.go
Updated the QA http rest engine of Move2Kube required for adding QA category enable/disable support to Move2Kube API https://github.com/konveyor/move2kube/issues/1155, https://github.com/konveyor/move2kube/issues/1151#issuecomment-1993816895. For the disabled categories, the QA engine should automatically consider the default answer as the input answer. 
=> fix: QA categories were being used only by the CLI engine 

transformer/dockerfilegenerator/rubydockerfiletransformer.go
Fixes - https://github.com/konveyor/move2kube/issues/1159
Move2Kube-UI detects all the services in the language-platforms, whereas earlier it was only detecting the Ruby service.
```yaml
apiVersion: move2kube.konveyor.io/v1alpha1
kind: Plan
metadata:
name: test
spec:
sourceDir: sources
services:
django:
- transformerName: Python-Dockerfile
paths:
MainPythonFilesPathType:
- language-platforms/language-platforms/django/manage.py
PythonFilesPathType:
- language-platforms/language-platforms/django/manage.py
RequirementsTxtPathType:
- language-platforms/language-platforms/django/requirements.txt
ServiceDirectories:
- language-platforms/language-platforms/django
configs:
OriginalName:
originalName: django
PythonConfig:
IsDjango: true
golang:
- transformerName: Golang-Dockerfile
paths: …
```
=> fix: When the m2kignore file is removed from language_platforms.zip then in the UI only the Ruby service is detected

Makefile
- fixes #1112 
- added conditions for `VERSION_METADATA`
=> fix: add condition for version_metadata in Makefile

filesystem/merger_test.go
i) this test for source and destination files with different content on execution of `MergeProcessFileCallBack` funcion
fixes a part of #881
=> test: added test for TestMergeProcessFileCallBack different content case

transformer/kubernetes/k8sschema/utils.go, transformer/kubernetes/parameterizer/parameterizer.go
Avoid these errors
```
ERRO[0001] Unable to parameterize for helm : there is no kind specified in the k8s resource map[resources:[enterprise-app-run-clone-build-push-triggertemplate.yaml frontend-vcapasenv-secret.yaml enterprise-app-clone-build-push-pipeline.yaml enterprise-app-git-event-triggerbinding.yaml enterprise-app-git-repo-eventlistener.yaml enterprise-app-image-registry-secret.yaml enterprise-app-ingress.yaml enterprise-app-tekton-triggers-admin-role.yaml enterprise-app-tekton-triggers-admin-rolebinding.yaml enterprise-app-tekton-triggers-admin-serviceaccount.yaml enterprise-app-clone-push-serviceaccount.yaml orders-vcapasenv-secret.yaml gateway-vcapasenv-secret.yaml]] 
ERRO[0001] Unable to parameterize /var/folders/81/pzmd85sj2d9dg02xgmd7wlhr0000gn/T/move2kube1886420936/environme …
```
=> fix: bug where all yaml files were treated as K8s yamls by the Parameterizer

assets/built-in/transformers/kubernetes/kubernetesversionchanger/transformer.yaml, assets/built-in/transformers/kubernetes/parameterizer/transformer.yaml, common/utils.go, transformer/transformer.go
feat: Added a new feature to sort transformers based on a label `move2kube.konveyor.io/sort-order` specified in the `transformer.yaml`. This is only the initial sorted order in which transformers are run and does not affect dependency related stuff like `MandatoryPassThrough`.
=> fix: K8s version change transformer was not being run sometimes because Parameterizer was running first

cmd/flags.go, cmd/transform.go
```
$ move2kube help transform
Transform artifacts using move2kube plan
Usage:
move2kube transform [flags]
Flags:
...................
--profile string                Path where the CPU profile file should be generated. By default we don't profile.
--profile-interval-ms int       Time (in milliseconds) between samples of the heap memory profile. Default 500ms. This flag is only used if the --profile-type flag is set to 'heap'. (default 500)
--profile-type string           The type of profiling that should be performed. Valid values are 'cpu' and 'heap' (Default 'cpu'). This flag is only used if the --profile flag is also provided. (default "cpu")
...................
$ move2kube transform -s language-platforms/ --profile m2kmem --profile-type heap --profile-interval-ms 250 --qa-skip …
```
=> feat: add a flag to profile the heap memory

common/vcs/git.go
Improving how git clone is performed:
- cleaning created local folder after 1st clone fails
- better log level to clearly inform the use of what's happening
Solves: https://github.com/konveyor/move2kube-api/issues/159
=> feat: improve git clone mechanism

.github/workflows/release.yml
https://github.com/konveyor/move2kube/actions/runs/10039196758/job/27744113100#step:4:259
=> test: cicd release failing with HTTP 404 error

.github/workflows/release.yml
See https://github.com/konveyor/move2kube/actions/runs/10047005376/job/27769138341#step:8:44
=> ci: use the fixed version of artifact upload action to avoid http 404 error
